// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file authority/query.proto (package pellchain.pellcore.authority, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Policies } from "./policies_pb.js";

/**
 * QueryGetPoliciesRequest is the request type for the Query/Policies RPC
 * method.
 *
 * @generated from message pellchain.pellcore.authority.QueryGetPoliciesRequest
 */
export declare class QueryGetPoliciesRequest extends Message<QueryGetPoliciesRequest> {
  constructor(data?: PartialMessage<QueryGetPoliciesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.authority.QueryGetPoliciesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetPoliciesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetPoliciesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetPoliciesRequest;

  static equals(a: QueryGetPoliciesRequest | PlainMessage<QueryGetPoliciesRequest> | undefined, b: QueryGetPoliciesRequest | PlainMessage<QueryGetPoliciesRequest> | undefined): boolean;
}

/**
 * QueryGetPoliciesResponse is the response type for the Query/Policies RPC
 * method.
 *
 * @generated from message pellchain.pellcore.authority.QueryPoliciesResponse
 */
export declare class QueryPoliciesResponse extends Message<QueryPoliciesResponse> {
  /**
   * @generated from field: pellchain.pellcore.authority.Policies policies = 1;
   */
  policies?: Policies;

  constructor(data?: PartialMessage<QueryPoliciesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.authority.QueryPoliciesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryPoliciesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryPoliciesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryPoliciesResponse;

  static equals(a: QueryPoliciesResponse | PlainMessage<QueryPoliciesResponse> | undefined, b: QueryPoliciesResponse | PlainMessage<QueryPoliciesResponse> | undefined): boolean;
}

