ARG TAG=latest
FROM ethereum/client-go:v1.10.26 AS geth
FROM pellnode:${TAG} AS pell
FROM node:18

# Download foundry
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="$PATH:/root/.foundry/bin"
RUN foundryup

RUN apt-get update && apt-get install -y openssh-server jq

WORKDIR /app
ARG GITHUB_TOKEN
RUN if [ -z "$GITHUB_TOKEN" ]; then echo "GITHUB_TOKEN is not set" && exit 1; fi
RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
RUN git clone https://github.com/0xPellNetwork/pell-middleware-contracts.git --branch v0.2.34 --depth 1

WORKDIR /app/pell-middleware-contracts

# install deps
RUN yarn install && forge install
RUN cd /app/pell-middleware-contracts/lib/pell-contracts && yarn install

ARG HTTP_PROXY
ARG HTTPS_PROXY
RUN forge compile && npx hardhat compile
RUN mkdir /run/sshd && chmod 0755 /run/sshd
RUN cat <<EOF > /root/.bashrc
export PATH="$PATH:/root/.foundry/bin"
export LOCALHOST_URL=http://eth:8545
export PELL_URL=http://pellcore0:8545
cd /app/pell-middleware-contracts/lib/pell-contracts
EOF

COPY contrib/localnet/ssh /root/.ssh
RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/*
COPY --from=geth /usr/local/bin/geth /usr/local/bin

# expose port
EXPOSE 8545
EXPOSE 22

# # run hardhat node
CMD /usr/sbin/sshd && sh ./scripts/docker_init_geth.sh
