// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xmsg/crosschain_fee_param.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Fee charged when constructing cross-chain xmsg from PEVM events
type CrosschainFeeParam struct {
	ChainId int64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// PellDelegationManagerOperatorSharesIncreased
	// PellDelegationManagerOperatorSharesDecreased
	DelegationOperatorShareEventFee cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=delegation_operator_share_event_fee,json=delegationOperatorShareEventFee,proto3,customtype=cosmossdk.io/math.Int" json:"delegation_operator_share_event_fee"`
	// PellDelegationManagerOperatorRegistered
	// PellDelegationManagerOperatorDetailsModified
	DelegationOperatorSyncFee cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=delegation_operator_sync_fee,json=delegationOperatorSyncFee,proto3,customtype=cosmossdk.io/math.Int" json:"delegation_operator_sync_fee"`
	// RegistryRouterSyncGroup
	RegistryRouterSyncGroupEventFee cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=registry_router_sync_group_event_fee,json=registryRouterSyncGroupEventFee,proto3,customtype=cosmossdk.io/math.Int" json:"registry_router_sync_group_event_fee"`
	DvsDefaultFee                   cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=dvs_default_fee,json=dvsDefaultFee,proto3,customtype=cosmossdk.io/math.Int" json:"dvs_default_fee"`
	PellSentEventFee                cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=pell_sent_event_fee,json=pellSentEventFee,proto3,customtype=cosmossdk.io/math.Int" json:"pell_sent_event_fee"`
	IsSupported                     bool                  `protobuf:"varint,9,opt,name=is_supported,json=isSupported,proto3" json:"is_supported,omitempty"`
}

func (m *CrosschainFeeParam) Reset()         { *m = CrosschainFeeParam{} }
func (m *CrosschainFeeParam) String() string { return proto.CompactTextString(m) }
func (*CrosschainFeeParam) ProtoMessage()    {}
func (*CrosschainFeeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dcb55132017eb0e, []int{0}
}
func (m *CrosschainFeeParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CrosschainFeeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CrosschainFeeParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CrosschainFeeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrosschainFeeParam.Merge(m, src)
}
func (m *CrosschainFeeParam) XXX_Size() int {
	return m.Size()
}
func (m *CrosschainFeeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CrosschainFeeParam.DiscardUnknown(m)
}

var xxx_messageInfo_CrosschainFeeParam proto.InternalMessageInfo

func (m *CrosschainFeeParam) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *CrosschainFeeParam) GetIsSupported() bool {
	if m != nil {
		return m.IsSupported
	}
	return false
}

func init() {
	proto.RegisterType((*CrosschainFeeParam)(nil), "xmsg.CrosschainFeeParam")
}

func init() { proto.RegisterFile("xmsg/crosschain_fee_param.proto", fileDescriptor_9dcb55132017eb0e) }

var fileDescriptor_9dcb55132017eb0e = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x07, 0xf0, 0x44, 0x94, 0xdd, 0xae, 0x01, 0x81, 0x02, 0x48, 0x5d, 0x04, 0x49, 0xf9, 0x38,
	0x54, 0x42, 0x24, 0x07, 0xde, 0x60, 0xa1, 0x8b, 0x56, 0x42, 0x02, 0xa5, 0x37, 0x0e, 0x58, 0xde,
	0x78, 0x36, 0xb1, 0x36, 0xc9, 0x58, 0xb6, 0x53, 0x6d, 0xde, 0x82, 0x67, 0xe0, 0x69, 0xf6, 0xd8,
	0x23, 0xe2, 0x50, 0xa1, 0xf6, 0x45, 0x90, 0x9d, 0x7e, 0xec, 0xa1, 0x87, 0xdc, 0x1c, 0xc7, 0xf3,
	0xfb, 0xcf, 0x48, 0x43, 0xa2, 0x9b, 0x4a, 0xe7, 0x49, 0xa6, 0x50, 0xeb, 0xac, 0x60, 0xa2, 0xa6,
	0x57, 0x00, 0x54, 0x32, 0xc5, 0xaa, 0x58, 0x2a, 0x34, 0x18, 0x0c, 0xec, 0x83, 0x17, 0xcf, 0x72,
	0xcc, 0xd1, 0x5d, 0x24, 0xf6, 0xd4, 0xfd, 0x7b, 0xf3, 0x7b, 0x40, 0x82, 0x4f, 0xbb, 0xd2, 0x73,
	0x80, 0xef, 0xb6, 0x30, 0x38, 0x25, 0xc3, 0xce, 0x12, 0x7c, 0xe4, 0x8f, 0xfd, 0xc9, 0xbd, 0xf4,
	0xd8, 0x7d, 0x5f, 0xf0, 0xe0, 0x9a, 0xbc, 0xe5, 0x50, 0x42, 0xce, 0x8c, 0xc0, 0x9a, 0xa2, 0x04,
	0xc5, 0x0c, 0x2a, 0xaa, 0x0b, 0xa6, 0x80, 0xc2, 0x1c, 0x6a, 0x63, 0x1b, 0x18, 0x0d, 0xc6, 0xfe,
	0xe4, 0xe4, 0xec, 0xd5, 0xed, 0x32, 0xf2, 0xfe, 0x2e, 0xa3, 0xe7, 0x19, 0xea, 0x0a, 0xb5, 0xe6,
	0xd7, 0xb1, 0xc0, 0xa4, 0x62, 0xa6, 0x88, 0x2f, 0x6a, 0x93, 0x46, 0x7b, 0xe9, 0xdb, 0x06, 0x9a,
	0x59, 0x67, 0x6a, 0x99, 0x73, 0x80, 0xe0, 0x27, 0x79, 0x79, 0x30, 0xac, 0xad, 0x33, 0x97, 0x72,
	0xbf, 0x4f, 0xca, 0xe9, 0x81, 0x94, 0xb6, 0xce, 0xac, 0x5f, 0x92, 0x77, 0x0a, 0x72, 0xa1, 0x8d,
	0x6a, 0xa9, 0xc2, 0xc6, 0xc0, 0xc6, 0xce, 0x15, 0x36, 0xf2, 0xce, 0x34, 0x47, 0xbd, 0xa6, 0xd9,
	0x52, 0xa9, 0x93, 0x6c, 0xc6, 0x17, 0xeb, 0xec, 0xa6, 0x99, 0x92, 0xc7, 0x7c, 0xae, 0x29, 0x87,
	0x2b, 0xd6, 0x94, 0x1d, 0x7c, 0xdc, 0x07, 0x7e, 0xc4, 0xe7, 0xfa, 0x73, 0x57, 0x64, 0x99, 0xaf,
	0xe4, 0xa9, 0x84, 0xb2, 0xa4, 0xda, 0x76, 0xb7, 0xef, 0x71, 0xd8, 0x87, 0x7a, 0x62, 0x2b, 0x67,
	0x50, 0x9b, 0x5d, 0x53, 0xaf, 0xc9, 0x43, 0xa1, 0xa9, 0x6e, 0xa4, 0x44, 0x65, 0x80, 0x8f, 0x4e,
	0xc6, 0xfe, 0x64, 0x98, 0x3e, 0x10, 0x7a, 0xb6, 0xbd, 0x3a, 0x9b, 0xde, 0xae, 0x42, 0x7f, 0xb1,
	0x0a, 0xfd, 0x7f, 0xab, 0xd0, 0xff, 0xb5, 0x0e, 0xbd, 0xc5, 0x3a, 0xf4, 0xfe, 0xac, 0x43, 0xef,
	0xc7, 0xfb, 0x5c, 0x98, 0xa2, 0xb9, 0x8c, 0x33, 0xac, 0x12, 0x2b, 0x7f, 0x70, 0x5b, 0xe2, 0x8e,
	0x19, 0x2a, 0x48, 0x6e, 0x12, 0xb7, 0x9c, 0xa6, 0x95, 0xa0, 0x2f, 0x8f, 0xdc, 0xca, 0x7d, 0xfc,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x13, 0x45, 0xce, 0xb1, 0x02, 0x00, 0x00,
}

func (m *CrosschainFeeParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrosschainFeeParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CrosschainFeeParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsSupported {
		i--
		if m.IsSupported {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.PellSentEventFee.Size()
		i -= size
		if _, err := m.PellSentEventFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.DvsDefaultFee.Size()
		i -= size
		if _, err := m.DvsDefaultFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.RegistryRouterSyncGroupEventFee.Size()
		i -= size
		if _, err := m.RegistryRouterSyncGroupEventFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.DelegationOperatorSyncFee.Size()
		i -= size
		if _, err := m.DelegationOperatorSyncFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DelegationOperatorShareEventFee.Size()
		i -= size
		if _, err := m.DelegationOperatorShareEventFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ChainId != 0 {
		i = encodeVarintCrosschainFeeParam(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCrosschainFeeParam(dAtA []byte, offset int, v uint64) int {
	offset -= sovCrosschainFeeParam(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CrosschainFeeParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovCrosschainFeeParam(uint64(m.ChainId))
	}
	l = m.DelegationOperatorShareEventFee.Size()
	n += 1 + l + sovCrosschainFeeParam(uint64(l))
	l = m.DelegationOperatorSyncFee.Size()
	n += 1 + l + sovCrosschainFeeParam(uint64(l))
	l = m.RegistryRouterSyncGroupEventFee.Size()
	n += 1 + l + sovCrosschainFeeParam(uint64(l))
	l = m.DvsDefaultFee.Size()
	n += 1 + l + sovCrosschainFeeParam(uint64(l))
	l = m.PellSentEventFee.Size()
	n += 1 + l + sovCrosschainFeeParam(uint64(l))
	if m.IsSupported {
		n += 2
	}
	return n
}

func sovCrosschainFeeParam(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCrosschainFeeParam(x uint64) (n int) {
	return sovCrosschainFeeParam(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CrosschainFeeParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCrosschainFeeParam
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrosschainFeeParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrosschainFeeParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationOperatorShareEventFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegationOperatorShareEventFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationOperatorSyncFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegationOperatorSyncFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryRouterSyncGroupEventFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegistryRouterSyncGroupEventFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DvsDefaultFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DvsDefaultFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellSentEventFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PellSentEventFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSupported", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSupported = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCrosschainFeeParam(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCrosschainFeeParam
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCrosschainFeeParam(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCrosschainFeeParam
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrosschainFeeParam
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCrosschainFeeParam
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCrosschainFeeParam
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCrosschainFeeParam
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCrosschainFeeParam        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCrosschainFeeParam          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCrosschainFeeParam = fmt.Errorf("proto: unexpected end of group")
)
