// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xmsg/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the xmsg modules genesis state.
type GenesisState struct {
	OutTxTrackerList    []OutTxTracker     `protobuf:"bytes,1,rep,name=out_tx_tracker_list,json=outTxTrackerList,proto3" json:"out_tx_tracker_list"`
	GasPriceList        []*GasPrice        `protobuf:"bytes,2,rep,name=gas_price_list,json=gasPriceList,proto3" json:"gas_price_list,omitempty"`
	Xmsgs               []*Xmsg            `protobuf:"bytes,3,rep,name=xmsgs,proto3" json:"xmsgs,omitempty"`
	LastBlockHeightList []*LastBlockHeight `protobuf:"bytes,4,rep,name=last_block_height_list,json=lastBlockHeightList,proto3" json:"last_block_height_list,omitempty"`
	InTxHashToXmsgList  []InTxHashToXmsg   `protobuf:"bytes,5,rep,name=in_tx_hash_to_xmsg_list,json=inTxHashToXmsgList,proto3" json:"in_tx_hash_to_xmsg_list"`
	InTxTrackerList     []InTxTracker      `protobuf:"bytes,6,rep,name=in_tx_tracker_list,json=inTxTrackerList,proto3" json:"in_tx_tracker_list"`
	FinalizedInbounds   []string           `protobuf:"bytes,7,rep,name=finalized_inbounds,json=finalizedInbounds,proto3" json:"finalized_inbounds,omitempty"`
	RateLimiterFlags    RateLimiterFlags   `protobuf:"bytes,8,opt,name=rate_limiter_flags,json=rateLimiterFlags,proto3" json:"rate_limiter_flags"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_967d4c6075811588, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOutTxTrackerList() []OutTxTracker {
	if m != nil {
		return m.OutTxTrackerList
	}
	return nil
}

func (m *GenesisState) GetGasPriceList() []*GasPrice {
	if m != nil {
		return m.GasPriceList
	}
	return nil
}

func (m *GenesisState) GetXmsgs() []*Xmsg {
	if m != nil {
		return m.Xmsgs
	}
	return nil
}

func (m *GenesisState) GetLastBlockHeightList() []*LastBlockHeight {
	if m != nil {
		return m.LastBlockHeightList
	}
	return nil
}

func (m *GenesisState) GetInTxHashToXmsgList() []InTxHashToXmsg {
	if m != nil {
		return m.InTxHashToXmsgList
	}
	return nil
}

func (m *GenesisState) GetInTxTrackerList() []InTxTracker {
	if m != nil {
		return m.InTxTrackerList
	}
	return nil
}

func (m *GenesisState) GetFinalizedInbounds() []string {
	if m != nil {
		return m.FinalizedInbounds
	}
	return nil
}

func (m *GenesisState) GetRateLimiterFlags() RateLimiterFlags {
	if m != nil {
		return m.RateLimiterFlags
	}
	return RateLimiterFlags{}
}

// Remove legacy types
type GenesisStateLegacy struct {
	Params              *Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	OutTxTrackerList    []OutTxTracker     `protobuf:"bytes,2,rep,name=out_tx_tracker_list,json=outTxTrackerList,proto3" json:"out_tx_tracker_list"`
	GasPriceList        []*GasPrice        `protobuf:"bytes,3,rep,name=gas_price_list,json=gasPriceList,proto3" json:"gas_price_list,omitempty"`
	Xmsgs               []*Xmsg            `protobuf:"bytes,4,rep,name=xmsgs,proto3" json:"xmsgs,omitempty"`
	LastBlockHeightList []*LastBlockHeight `protobuf:"bytes,5,rep,name=last_block_height_list,json=lastBlockHeightList,proto3" json:"last_block_height_list,omitempty"`
	InTxHashToXmsgList  []InTxHashToXmsg   `protobuf:"bytes,6,rep,name=in_tx_hash_to_xmsg_list,json=inTxHashToXmsgList,proto3" json:"in_tx_hash_to_xmsg_list"`
	InTxTrackerList     []InTxTracker      `protobuf:"bytes,7,rep,name=in_tx_tracker_list,json=inTxTrackerList,proto3" json:"in_tx_tracker_list"`
	FinalizedInbounds   []string           `protobuf:"bytes,8,rep,name=finalized_inbounds,json=finalizedInbounds,proto3" json:"finalized_inbounds,omitempty"`
}

func (m *GenesisStateLegacy) Reset()         { *m = GenesisStateLegacy{} }
func (m *GenesisStateLegacy) String() string { return proto.CompactTextString(m) }
func (*GenesisStateLegacy) ProtoMessage()    {}
func (*GenesisStateLegacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_967d4c6075811588, []int{1}
}
func (m *GenesisStateLegacy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisStateLegacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisStateLegacy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisStateLegacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisStateLegacy.Merge(m, src)
}
func (m *GenesisStateLegacy) XXX_Size() int {
	return m.Size()
}
func (m *GenesisStateLegacy) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisStateLegacy.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisStateLegacy proto.InternalMessageInfo

func (m *GenesisStateLegacy) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisStateLegacy) GetOutTxTrackerList() []OutTxTracker {
	if m != nil {
		return m.OutTxTrackerList
	}
	return nil
}

func (m *GenesisStateLegacy) GetGasPriceList() []*GasPrice {
	if m != nil {
		return m.GasPriceList
	}
	return nil
}

func (m *GenesisStateLegacy) GetXmsgs() []*Xmsg {
	if m != nil {
		return m.Xmsgs
	}
	return nil
}

func (m *GenesisStateLegacy) GetLastBlockHeightList() []*LastBlockHeight {
	if m != nil {
		return m.LastBlockHeightList
	}
	return nil
}

func (m *GenesisStateLegacy) GetInTxHashToXmsgList() []InTxHashToXmsg {
	if m != nil {
		return m.InTxHashToXmsgList
	}
	return nil
}

func (m *GenesisStateLegacy) GetInTxTrackerList() []InTxTracker {
	if m != nil {
		return m.InTxTrackerList
	}
	return nil
}

func (m *GenesisStateLegacy) GetFinalizedInbounds() []string {
	if m != nil {
		return m.FinalizedInbounds
	}
	return nil
}

// enabled param
type Params struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_967d4c6075811588, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "xmsg.GenesisState")
	proto.RegisterType((*GenesisStateLegacy)(nil), "xmsg.GenesisStateLegacy")
	proto.RegisterType((*Params)(nil), "xmsg.Params")
}

func init() { proto.RegisterFile("xmsg/genesis.proto", fileDescriptor_967d4c6075811588) }

var fileDescriptor_967d4c6075811588 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6b, 0xdb, 0x30,
	0x18, 0xc6, 0xe3, 0xe6, 0xef, 0xd4, 0xd0, 0xae, 0x6a, 0xd6, 0x79, 0x61, 0xf3, 0x42, 0xd8, 0x21,
	0x30, 0x9a, 0x40, 0xb7, 0x4f, 0x10, 0xb6, 0xa5, 0x2d, 0x81, 0x16, 0x2f, 0x87, 0xb1, 0x8b, 0x50,
	0x1c, 0x55, 0x16, 0x55, 0xac, 0x60, 0x29, 0xe0, 0xee, 0x3b, 0x0c, 0xf6, 0xb1, 0x7a, 0xec, 0x71,
	0xa7, 0x31, 0x92, 0xf3, 0xbe, 0xc3, 0xf0, 0x2b, 0xb7, 0x8d, 0x1b, 0x7a, 0x28, 0xe4, 0x26, 0x3f,
	0xbf, 0xf7, 0x7d, 0x64, 0xe9, 0x7d, 0x10, 0xc2, 0xc9, 0x54, 0xf3, 0x1e, 0x67, 0x11, 0xd3, 0x42,
	0x77, 0x67, 0xb1, 0x32, 0x0a, 0x97, 0x52, 0xad, 0xd9, 0xe0, 0x8a, 0x2b, 0x10, 0x7a, 0xe9, 0xca,
	0xb2, 0x66, 0xc3, 0xd6, 0x53, 0x4d, 0x66, 0xb1, 0x08, 0x58, 0xa6, 0xbe, 0x01, 0x55, 0x44, 0xc4,
	0x24, 0x24, 0xa4, 0x3a, 0x24, 0x46, 0x91, 0x54, 0xca, 0xb0, 0xbb, 0x82, 0x4d, 0x4c, 0x83, 0x4b,
	0x16, 0x67, 0xe4, 0x35, 0x10, 0x49, 0xb5, 0x21, 0x63, 0xa9, 0x82, 0x4b, 0x12, 0x32, 0xc1, 0x43,
	0x93, 0xd1, 0x57, 0x40, 0xd5, 0xdc, 0xac, 0x37, 0xda, 0x1d, 0x63, 0x6a, 0x18, 0x91, 0x62, 0x2a,
	0x0c, 0x8b, 0xc9, 0x85, 0xa4, 0x3c, 0x3b, 0x42, 0x73, 0x17, 0xf0, 0xfd, 0x2f, 0xb4, 0x7f, 0x96,
	0x50, 0x7d, 0x60, 0x4f, 0xf9, 0xd5, 0x50, 0xc3, 0xf0, 0x00, 0xed, 0xe7, 0x8d, 0x89, 0x14, 0xda,
	0xb8, 0x4e, 0xab, 0xd8, 0xd9, 0x3e, 0xc2, 0x5d, 0x68, 0x3d, 0x9b, 0x9b, 0x51, 0x32, 0xb2, 0xb8,
	0x5f, 0xba, 0xfe, 0xf3, 0xb6, 0xe0, 0x3f, 0x57, 0x2b, 0xda, 0x50, 0x68, 0x83, 0x3f, 0xa2, 0x9d,
	0xbb, 0xeb, 0xb0, 0x1e, 0x5b, 0xe0, 0xb1, 0x63, 0x3d, 0x06, 0x54, 0x9f, 0xa7, 0xc8, 0xaf, 0xf3,
	0x6c, 0x05, 0x5d, 0x2d, 0x54, 0x4e, 0xb1, 0x76, 0x8b, 0x50, 0x8c, 0x6c, 0xf1, 0xb7, 0xa9, 0xe6,
	0xbe, 0x05, 0xf8, 0x14, 0x1d, 0xac, 0xdd, 0x8b, 0xf5, 0x2f, 0x41, 0xcb, 0x0b, 0xdb, 0x32, 0xa4,
	0xda, 0xf4, 0xd3, 0x92, 0x63, 0xa8, 0xf0, 0xf7, 0x65, 0x5e, 0x80, 0xdd, 0xce, 0xd0, 0xcb, 0xf5,
	0xe1, 0x58, 0xb3, 0x32, 0x98, 0x35, 0xac, 0xd9, 0x49, 0x34, 0x4a, 0x8e, 0xa9, 0x0e, 0x47, 0x2a,
	0xfd, 0x93, 0xec, 0xc8, 0x58, 0xe4, 0x54, 0x30, 0xfc, 0x84, 0x70, 0x6e, 0x9c, 0xd6, 0xab, 0x02,
	0x5e, 0x7b, 0xf7, 0x5e, 0xf9, 0xbb, 0xdb, 0x15, 0x51, 0xfe, 0xea, 0x0e, 0x11, 0xbe, 0x10, 0x11,
	0x95, 0xe2, 0x07, 0x9b, 0x10, 0x11, 0x8d, 0xd5, 0x3c, 0x9a, 0x68, 0xb7, 0xda, 0x2a, 0x76, 0x9e,
	0xf9, 0x7b, 0x77, 0xe4, 0x24, 0x03, 0xf8, 0x14, 0xe1, 0xf5, 0x81, 0xbb, 0xb5, 0x96, 0xd3, 0xd9,
	0x3e, 0x3a, 0xb0, 0x9b, 0xfa, 0xd4, 0xb0, 0xa1, 0xc5, 0x5f, 0x52, 0x7a, 0x3b, 0xb5, 0xf8, 0x81,
	0xde, 0xfe, 0x57, 0x44, 0x78, 0x35, 0x0f, 0x43, 0xc6, 0x69, 0x70, 0x85, 0xdf, 0xa1, 0xca, 0x8c,
	0xc6, 0x74, 0xaa, 0x5d, 0x07, 0x6c, 0xeb, 0xd6, 0xf6, 0x1c, 0x34, 0x3f, 0x63, 0x8f, 0x65, 0x67,
	0x6b, 0x03, 0xd9, 0x29, 0x3e, 0x25, 0x3b, 0xa5, 0xa7, 0x67, 0xa7, 0xbc, 0xc9, 0xec, 0x54, 0x36,
	0x98, 0x9d, 0xea, 0x46, 0xb2, 0x53, 0x7b, 0x24, 0x3b, 0xed, 0x36, 0xaa, 0xd8, 0x21, 0x62, 0x17,
	0x55, 0x59, 0x44, 0xc7, 0x92, 0x4d, 0x60, 0xc6, 0x35, 0xff, 0xf6, 0xb3, 0xff, 0xf9, 0x7a, 0xe1,
	0x39, 0x37, 0x0b, 0xcf, 0xf9, 0xbb, 0xf0, 0x9c, 0x5f, 0x4b, 0xaf, 0x70, 0xb3, 0xf4, 0x0a, 0xbf,
	0x97, 0x5e, 0xe1, 0xfb, 0x7b, 0x2e, 0x4c, 0x38, 0x1f, 0x77, 0x03, 0x35, 0xed, 0xcd, 0x98, 0x94,
	0x87, 0x41, 0x48, 0x45, 0x04, 0xcb, 0x40, 0xc5, 0xac, 0x97, 0xc0, 0x53, 0xd3, 0x33, 0x57, 0x33,
	0xa6, 0xc7, 0x15, 0x78, 0x71, 0x3e, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x67, 0x6f, 0x2b,
	0x5b, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RateLimiterFlags.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.FinalizedInbounds) > 0 {
		for iNdEx := len(m.FinalizedInbounds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FinalizedInbounds[iNdEx])
			copy(dAtA[i:], m.FinalizedInbounds[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.FinalizedInbounds[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.InTxTrackerList) > 0 {
		for iNdEx := len(m.InTxTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InTxTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.InTxHashToXmsgList) > 0 {
		for iNdEx := len(m.InTxHashToXmsgList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InTxHashToXmsgList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for iNdEx := len(m.LastBlockHeightList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastBlockHeightList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Xmsgs) > 0 {
		for iNdEx := len(m.Xmsgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Xmsgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.GasPriceList) > 0 {
		for iNdEx := len(m.GasPriceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPriceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.OutTxTrackerList) > 0 {
		for iNdEx := len(m.OutTxTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutTxTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisStateLegacy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisStateLegacy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisStateLegacy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FinalizedInbounds) > 0 {
		for iNdEx := len(m.FinalizedInbounds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FinalizedInbounds[iNdEx])
			copy(dAtA[i:], m.FinalizedInbounds[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.FinalizedInbounds[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.InTxTrackerList) > 0 {
		for iNdEx := len(m.InTxTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InTxTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.InTxHashToXmsgList) > 0 {
		for iNdEx := len(m.InTxHashToXmsgList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InTxHashToXmsgList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for iNdEx := len(m.LastBlockHeightList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastBlockHeightList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Xmsgs) > 0 {
		for iNdEx := len(m.Xmsgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Xmsgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.GasPriceList) > 0 {
		for iNdEx := len(m.GasPriceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPriceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.OutTxTrackerList) > 0 {
		for iNdEx := len(m.OutTxTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutTxTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OutTxTrackerList) > 0 {
		for _, e := range m.OutTxTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GasPriceList) > 0 {
		for _, e := range m.GasPriceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Xmsgs) > 0 {
		for _, e := range m.Xmsgs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for _, e := range m.LastBlockHeightList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InTxHashToXmsgList) > 0 {
		for _, e := range m.InTxHashToXmsgList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InTxTrackerList) > 0 {
		for _, e := range m.InTxTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FinalizedInbounds) > 0 {
		for _, s := range m.FinalizedInbounds {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.RateLimiterFlags.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisStateLegacy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.OutTxTrackerList) > 0 {
		for _, e := range m.OutTxTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GasPriceList) > 0 {
		for _, e := range m.GasPriceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Xmsgs) > 0 {
		for _, e := range m.Xmsgs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for _, e := range m.LastBlockHeightList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InTxHashToXmsgList) > 0 {
		for _, e := range m.InTxHashToXmsgList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InTxTrackerList) > 0 {
		for _, e := range m.InTxTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FinalizedInbounds) > 0 {
		for _, s := range m.FinalizedInbounds {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutTxTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutTxTrackerList = append(m.OutTxTrackerList, OutTxTracker{})
			if err := m.OutTxTrackerList[len(m.OutTxTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPriceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPriceList = append(m.GasPriceList, &GasPrice{})
			if err := m.GasPriceList[len(m.GasPriceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Xmsgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Xmsgs = append(m.Xmsgs, &Xmsg{})
			if err := m.Xmsgs[len(m.Xmsgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockHeightList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastBlockHeightList = append(m.LastBlockHeightList, &LastBlockHeight{})
			if err := m.LastBlockHeightList[len(m.LastBlockHeightList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxHashToXmsgList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxHashToXmsgList = append(m.InTxHashToXmsgList, InTxHashToXmsg{})
			if err := m.InTxHashToXmsgList[len(m.InTxHashToXmsgList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxTrackerList = append(m.InTxTrackerList, InTxTracker{})
			if err := m.InTxTrackerList[len(m.InTxTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedInbounds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalizedInbounds = append(m.FinalizedInbounds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimiterFlags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RateLimiterFlags.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisStateLegacy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisStateLegacy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisStateLegacy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutTxTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutTxTrackerList = append(m.OutTxTrackerList, OutTxTracker{})
			if err := m.OutTxTrackerList[len(m.OutTxTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPriceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPriceList = append(m.GasPriceList, &GasPrice{})
			if err := m.GasPriceList[len(m.GasPriceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Xmsgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Xmsgs = append(m.Xmsgs, &Xmsg{})
			if err := m.Xmsgs[len(m.Xmsgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockHeightList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastBlockHeightList = append(m.LastBlockHeightList, &LastBlockHeight{})
			if err := m.LastBlockHeightList[len(m.LastBlockHeightList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxHashToXmsgList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxHashToXmsgList = append(m.InTxHashToXmsgList, InTxHashToXmsg{})
			if err := m.InTxHashToXmsgList[len(m.InTxHashToXmsgList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxTrackerList = append(m.InTxTrackerList, InTxTracker{})
			if err := m.InTxTrackerList[len(m.InTxTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedInbounds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalizedInbounds = append(m.FinalizedInbounds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
