// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xmsg/rate_limiter_flags.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// rate limiter setting
type RateLimiterFlags struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// window in blocks
	Window int64 `protobuf:"varint,2,opt,name=window,proto3" json:"window,omitempty"`
	// rate in apell per block
	Rate cosmossdk_io_math.Uint `protobuf:"bytes,3,opt,name=rate,proto3,customtype=cosmossdk.io/math.Uint" json:"rate"`
}

func (m *RateLimiterFlags) Reset()         { *m = RateLimiterFlags{} }
func (m *RateLimiterFlags) String() string { return proto.CompactTextString(m) }
func (*RateLimiterFlags) ProtoMessage()    {}
func (*RateLimiterFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_109880666c405d93, []int{0}
}
func (m *RateLimiterFlags) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RateLimiterFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RateLimiterFlags.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RateLimiterFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimiterFlags.Merge(m, src)
}
func (m *RateLimiterFlags) XXX_Size() int {
	return m.Size()
}
func (m *RateLimiterFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimiterFlags.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimiterFlags proto.InternalMessageInfo

func (m *RateLimiterFlags) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *RateLimiterFlags) GetWindow() int64 {
	if m != nil {
		return m.Window
	}
	return 0
}

func init() {
	proto.RegisterType((*RateLimiterFlags)(nil), "xmsg.RateLimiterFlags")
}

func init() { proto.RegisterFile("xmsg/rate_limiter_flags.proto", fileDescriptor_109880666c405d93) }

var fileDescriptor_109880666c405d93 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xad, 0xc8, 0x2d, 0x4e,
	0xd7, 0x2f, 0x4a, 0x2c, 0x49, 0x8d, 0xcf, 0xc9, 0xcc, 0xcd, 0x2c, 0x49, 0x2d, 0x8a, 0x4f, 0xcb,
	0x49, 0x4c, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x4b, 0x89, 0xa4,
	0xe7, 0xa7, 0xe7, 0x83, 0x05, 0xf4, 0x41, 0x2c, 0x88, 0x9c, 0x52, 0x05, 0x97, 0x40, 0x50, 0x62,
	0x49, 0xaa, 0x0f, 0x44, 0x9b, 0x1b, 0x48, 0x97, 0x90, 0x04, 0x17, 0x7b, 0x6a, 0x5e, 0x62, 0x52,
	0x4e, 0x6a, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x8c, 0x2b, 0x24, 0xc6, 0xc5, 0x56,
	0x9e, 0x99, 0x97, 0x92, 0x5f, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe5, 0x09, 0x19,
	0x71, 0xb1, 0x80, 0x6c, 0x97, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x74, 0x92, 0x3b, 0x71, 0x4f, 0x9e,
	0xe1, 0xd6, 0x3d, 0x79, 0xb1, 0xe4, 0xfc, 0xe2, 0xdc, 0xfc, 0xe2, 0xe2, 0x94, 0x6c, 0xbd, 0xcc,
	0x7c, 0xfd, 0xdc, 0xc4, 0x92, 0x0c, 0xbd, 0xd0, 0xcc, 0xbc, 0x92, 0x20, 0xb0, 0x5a, 0x27, 0xd7,
	0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39,
	0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0xd2, 0x4e, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x48, 0xcd, 0xc9, 0xd1, 0x4d, 0xce, 0x48, 0xcc, 0xcc,
	0x03, 0x33, 0x93, 0xf3, 0x8b, 0x52, 0xf5, 0x2b, 0xf4, 0xc1, 0xfe, 0x2d, 0xa9, 0x2c, 0x48, 0x2d,
	0x4e, 0x62, 0x03, 0xfb, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xae, 0xe9, 0x87, 0x04,
	0x01, 0x00, 0x00,
}

func (m *RateLimiterFlags) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RateLimiterFlags) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RateLimiterFlags) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Rate.Size()
		i -= size
		if _, err := m.Rate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRateLimiterFlags(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Window != 0 {
		i = encodeVarintRateLimiterFlags(dAtA, i, uint64(m.Window))
		i--
		dAtA[i] = 0x10
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRateLimiterFlags(dAtA []byte, offset int, v uint64) int {
	offset -= sovRateLimiterFlags(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RateLimiterFlags) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if m.Window != 0 {
		n += 1 + sovRateLimiterFlags(uint64(m.Window))
	}
	l = m.Rate.Size()
	n += 1 + l + sovRateLimiterFlags(uint64(l))
	return n
}

func sovRateLimiterFlags(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRateLimiterFlags(x uint64) (n int) {
	return sovRateLimiterFlags(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RateLimiterFlags) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRateLimiterFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RateLimiterFlags: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RateLimiterFlags: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRateLimiterFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Window", wireType)
			}
			m.Window = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRateLimiterFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Window |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRateLimiterFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRateLimiterFlags
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRateLimiterFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRateLimiterFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRateLimiterFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRateLimiterFlags(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRateLimiterFlags
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRateLimiterFlags
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRateLimiterFlags
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRateLimiterFlags
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRateLimiterFlags
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRateLimiterFlags
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRateLimiterFlags        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRateLimiterFlags          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRateLimiterFlags = fmt.Errorf("proto: unexpected end of group")
)
