// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/ballot.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// relayer vote type
type VoteType int32

const (
	// success
	VoteType_SUCCESS_OBSERVATION VoteType = 0
	// Failure observation means , the the message that
	// this voter is observing failed / reverted . It does
	// not mean it was unable to observe.
	VoteType_FAILURE_OBSERVATION VoteType = 1
	// not yet voted
	VoteType_NOT_YET_VOTED VoteType = 2
)

var VoteType_name = map[int32]string{
	0: "SUCCESS_OBSERVATION",
	1: "FAILURE_OBSERVATION",
	2: "NOT_YET_VOTED",
}

var VoteType_value = map[string]int32{
	"SUCCESS_OBSERVATION": 0,
	"FAILURE_OBSERVATION": 1,
	"NOT_YET_VOTED":       2,
}

func (x VoteType) String() string {
	return proto.EnumName(VoteType_name, int32(x))
}

func (VoteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b650a02890f112a5, []int{0}
}

// ballot status
type BallotStatus int32

const (
	// successful ballot
	BallotStatus_BALLOT_FINALIZED_SUCCESS_OBSERVATION BallotStatus = 0
	// failure ballot
	BallotStatus_BALLOT_FINALIZED_FAILURE_OBSERVATION BallotStatus = 1
	// progress ballot
	BallotStatus_BALLOT_IN_PROGRESS BallotStatus = 2
)

var BallotStatus_name = map[int32]string{
	0: "BALLOT_FINALIZED_SUCCESS_OBSERVATION",
	1: "BALLOT_FINALIZED_FAILURE_OBSERVATION",
	2: "BALLOT_IN_PROGRESS",
}

var BallotStatus_value = map[string]int32{
	"BALLOT_FINALIZED_SUCCESS_OBSERVATION": 0,
	"BALLOT_FINALIZED_FAILURE_OBSERVATION": 1,
	"BALLOT_IN_PROGRESS":                   2,
}

func (x BallotStatus) String() string {
	return proto.EnumName(BallotStatus_name, int32(x))
}

func (BallotStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b650a02890f112a5, []int{1}
}

// ballot
type Ballot struct {
	Index                string                      `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	BallotIdentifier     string                      `protobuf:"bytes,2,opt,name=ballot_identifier,json=ballotIdentifier,proto3" json:"ballot_identifier,omitempty"`
	VoterList            []string                    `protobuf:"bytes,3,rep,name=voter_list,json=voterList,proto3" json:"voter_list,omitempty"`
	Votes                []VoteType                  `protobuf:"varint,4,rep,packed,name=votes,proto3,enum=relayer.VoteType" json:"votes,omitempty"`
	ObservationType      ObservationType             `protobuf:"varint,5,opt,name=observation_type,json=observationType,proto3,enum=relayer.ObservationType" json:"observation_type,omitempty"`
	BallotThreshold      cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=ballot_threshold,json=ballotThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ballot_threshold"`
	BallotStatus         BallotStatus                `protobuf:"varint,7,opt,name=ballot_status,json=ballotStatus,proto3,enum=relayer.BallotStatus" json:"ballot_status,omitempty"`
	BallotCreationHeight int64                       `protobuf:"varint,8,opt,name=ballot_creation_height,json=ballotCreationHeight,proto3" json:"ballot_creation_height,omitempty"`
}

func (m *Ballot) Reset()         { *m = Ballot{} }
func (m *Ballot) String() string { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()    {}
func (*Ballot) Descriptor() ([]byte, []int) {
	return fileDescriptor_b650a02890f112a5, []int{0}
}
func (m *Ballot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ballot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ballot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ballot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ballot.Merge(m, src)
}
func (m *Ballot) XXX_Size() int {
	return m.Size()
}
func (m *Ballot) XXX_DiscardUnknown() {
	xxx_messageInfo_Ballot.DiscardUnknown(m)
}

var xxx_messageInfo_Ballot proto.InternalMessageInfo

func (m *Ballot) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Ballot) GetBallotIdentifier() string {
	if m != nil {
		return m.BallotIdentifier
	}
	return ""
}

func (m *Ballot) GetVoterList() []string {
	if m != nil {
		return m.VoterList
	}
	return nil
}

func (m *Ballot) GetVotes() []VoteType {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Ballot) GetObservationType() ObservationType {
	if m != nil {
		return m.ObservationType
	}
	return ObservationType_EMPTY_OBSERVER_TYPE
}

func (m *Ballot) GetBallotStatus() BallotStatus {
	if m != nil {
		return m.BallotStatus
	}
	return BallotStatus_BALLOT_FINALIZED_SUCCESS_OBSERVATION
}

func (m *Ballot) GetBallotCreationHeight() int64 {
	if m != nil {
		return m.BallotCreationHeight
	}
	return 0
}

// ballot list for block height
type BallotListForHeight struct {
	Height           int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BallotsIndexList []string `protobuf:"bytes,2,rep,name=ballots_index_list,json=ballotsIndexList,proto3" json:"ballots_index_list,omitempty"`
}

func (m *BallotListForHeight) Reset()         { *m = BallotListForHeight{} }
func (m *BallotListForHeight) String() string { return proto.CompactTextString(m) }
func (*BallotListForHeight) ProtoMessage()    {}
func (*BallotListForHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_b650a02890f112a5, []int{1}
}
func (m *BallotListForHeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BallotListForHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BallotListForHeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BallotListForHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BallotListForHeight.Merge(m, src)
}
func (m *BallotListForHeight) XXX_Size() int {
	return m.Size()
}
func (m *BallotListForHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_BallotListForHeight.DiscardUnknown(m)
}

var xxx_messageInfo_BallotListForHeight proto.InternalMessageInfo

func (m *BallotListForHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BallotListForHeight) GetBallotsIndexList() []string {
	if m != nil {
		return m.BallotsIndexList
	}
	return nil
}

func init() {
	proto.RegisterEnum("relayer.VoteType", VoteType_name, VoteType_value)
	proto.RegisterEnum("relayer.BallotStatus", BallotStatus_name, BallotStatus_value)
	proto.RegisterType((*Ballot)(nil), "relayer.Ballot")
	proto.RegisterType((*BallotListForHeight)(nil), "relayer.BallotListForHeight")
}

func init() { proto.RegisterFile("relayer/ballot.proto", fileDescriptor_b650a02890f112a5) }

var fileDescriptor_b650a02890f112a5 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9b, 0x36, 0x6d, 0x57, 0xfd, 0x48, 0xb6, 0x69, 0xb0, 0x82, 0x70, 0xa3, 0x82, 0x84,
	0x55, 0xc0, 0x96, 0x0a, 0x27, 0x6e, 0xf9, 0x70, 0xa8, 0x25, 0x2b, 0x46, 0xb6, 0x13, 0x89, 0x72,
	0xb0, 0x1c, 0x67, 0x89, 0x57, 0x38, 0xd9, 0xc8, 0xbb, 0xad, 0x9a, 0x1b, 0x3f, 0x81, 0x33, 0x67,
	0x0e, 0xfc, 0x94, 0x1e, 0x7b, 0x44, 0x1c, 0x2a, 0x94, 0xfc, 0x11, 0xe4, 0x5d, 0x3b, 0xb4, 0x52,
	0x4e, 0xde, 0x79, 0x6f, 0xde, 0xcc, 0xf3, 0xcc, 0x2e, 0xa8, 0x26, 0x28, 0x0e, 0xe6, 0x28, 0xd1,
	0x87, 0x41, 0x1c, 0x13, 0xa6, 0xcd, 0x12, 0xc2, 0x08, 0xdc, 0xce, 0xd0, 0x7a, 0x75, 0x4c, 0xc6,
	0x84, 0x63, 0x7a, 0x7a, 0x12, 0x74, 0xfd, 0x38, 0x17, 0x65, 0x5f, 0x01, 0x9f, 0xfe, 0x28, 0x82,
	0x52, 0x8b, 0x97, 0x81, 0x55, 0xb0, 0x85, 0xa7, 0x23, 0x74, 0x23, 0x4b, 0x0d, 0x49, 0xdd, 0x75,
	0x44, 0x00, 0x5f, 0x81, 0x8a, 0x68, 0xe3, 0xe3, 0x11, 0x9a, 0x32, 0xfc, 0x05, 0xa3, 0x44, 0xde,
	0xe0, 0x19, 0x65, 0x41, 0x98, 0x2b, 0x1c, 0x3e, 0x03, 0xe0, 0x9a, 0x30, 0x94, 0xf8, 0x31, 0xa6,
	0x4c, 0x2e, 0x36, 0x8a, 0xea, 0xae, 0xb3, 0xcb, 0x11, 0x0b, 0x53, 0x06, 0x5f, 0x82, 0xad, 0x34,
	0xa0, 0xf2, 0x66, 0xa3, 0xa8, 0x1e, 0x9c, 0x57, 0xb4, 0xdc, 0xcb, 0x80, 0x30, 0xe4, 0xcd, 0x67,
	0xc8, 0x11, 0x3c, 0x6c, 0x83, 0x32, 0x19, 0x52, 0x94, 0x5c, 0x07, 0x0c, 0x93, 0xa9, 0xcf, 0xe6,
	0x33, 0x24, 0x6f, 0x35, 0x24, 0xf5, 0xe0, 0x5c, 0x5e, 0x69, 0xec, 0xff, 0x09, 0x5c, 0x7a, 0x48,
	0x1e, 0x03, 0xb0, 0x07, 0x32, 0x83, 0x3e, 0x8b, 0x12, 0x44, 0x23, 0x12, 0x8f, 0xe4, 0x52, 0x6a,
	0xbc, 0xf5, 0xfc, 0xf6, 0xfe, 0xa4, 0xf0, 0xe7, 0xfe, 0xe4, 0x69, 0x48, 0xe8, 0x84, 0x50, 0x3a,
	0xfa, 0xaa, 0x61, 0xa2, 0x4f, 0x02, 0x16, 0x69, 0x16, 0x1a, 0x07, 0xe1, 0xbc, 0x83, 0x42, 0xe7,
	0x50, 0x88, 0xbd, 0x5c, 0x0b, 0xdf, 0x83, 0xfd, 0xac, 0x1e, 0x65, 0x01, 0xbb, 0xa2, 0xf2, 0x36,
	0x77, 0x74, 0xbc, 0x72, 0x24, 0xe6, 0xe8, 0x72, 0xd2, 0xd9, 0x1b, 0x3e, 0x88, 0xe0, 0x3b, 0x50,
	0xcb, 0xb4, 0x61, 0x82, 0xc4, 0x4f, 0x45, 0x08, 0x8f, 0x23, 0x26, 0xef, 0x34, 0x24, 0xb5, 0xe8,
	0x54, 0x05, 0xdb, 0xce, 0xc8, 0x0b, 0xce, 0x9d, 0x7e, 0x06, 0x47, 0xa2, 0x66, 0x3a, 0xbd, 0x2e,
	0x49, 0x04, 0x0c, 0x6b, 0xa0, 0x94, 0x89, 0x25, 0x2e, 0xce, 0x22, 0xf8, 0x1a, 0x40, 0x51, 0x86,
	0xfa, 0x7c, 0x77, 0x62, 0x0b, 0x1b, 0x7c, 0x0b, 0xd9, 0x28, 0xa8, 0x99, 0x12, 0x69, 0xb9, 0xb3,
	0x3e, 0xd8, 0xc9, 0xc7, 0x0e, 0x9f, 0x80, 0x23, 0xb7, 0xdf, 0x6e, 0x1b, 0xae, 0xeb, 0xdb, 0x2d,
	0xd7, 0x70, 0x06, 0x4d, 0xcf, 0xb4, 0x7b, 0xe5, 0x42, 0x4a, 0x74, 0x9b, 0xa6, 0xd5, 0x77, 0x8c,
	0x47, 0x84, 0x04, 0x2b, 0x60, 0xbf, 0x67, 0x7b, 0xfe, 0x27, 0xc3, 0xf3, 0x07, 0xb6, 0x67, 0x74,
	0xca, 0x1b, 0xf5, 0xcd, 0x5f, 0x3f, 0x15, 0xe9, 0xec, 0x9b, 0x04, 0xf6, 0x1e, 0x0e, 0x02, 0xaa,
	0xe0, 0x45, 0xab, 0x69, 0x59, 0xb6, 0xe7, 0x77, 0xcd, 0x5e, 0xd3, 0x32, 0x2f, 0x8d, 0x8e, 0xbf,
	0xbe, 0xd9, 0xba, 0xcc, 0xf5, 0xdd, 0x6b, 0x00, 0x66, 0x99, 0x66, 0xcf, 0xff, 0xe8, 0xd8, 0x1f,
	0x1c, 0xc3, 0x75, 0x73, 0x0b, 0xad, 0x8b, 0xdb, 0x85, 0x22, 0xdd, 0x2d, 0x14, 0xe9, 0xef, 0x42,
	0x91, 0xbe, 0x2f, 0x95, 0xc2, 0xdd, 0x52, 0x29, 0xfc, 0x5e, 0x2a, 0x85, 0x4b, 0x6d, 0x8c, 0x59,
	0x74, 0x35, 0xd4, 0x42, 0x32, 0xd1, 0x67, 0x28, 0x8e, 0xdf, 0x84, 0x51, 0x80, 0xa7, 0xfc, 0x18,
	0x92, 0x04, 0xe9, 0x37, 0xf9, 0xeb, 0xd0, 0xd3, 0x2b, 0x47, 0x87, 0x25, 0xfe, 0x48, 0xde, 0xfe,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x80, 0x7b, 0x27, 0x70, 0x72, 0x03, 0x00, 0x00,
}

func (m *Ballot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ballot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ballot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BallotCreationHeight != 0 {
		i = encodeVarintBallot(dAtA, i, uint64(m.BallotCreationHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.BallotStatus != 0 {
		i = encodeVarintBallot(dAtA, i, uint64(m.BallotStatus))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.BallotThreshold.Size()
		i -= size
		if _, err := m.BallotThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBallot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.ObservationType != 0 {
		i = encodeVarintBallot(dAtA, i, uint64(m.ObservationType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Votes) > 0 {
		dAtA2 := make([]byte, len(m.Votes)*10)
		var j1 int
		for _, num := range m.Votes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintBallot(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VoterList) > 0 {
		for iNdEx := len(m.VoterList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.VoterList[iNdEx])
			copy(dAtA[i:], m.VoterList[iNdEx])
			i = encodeVarintBallot(dAtA, i, uint64(len(m.VoterList[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.BallotIdentifier) > 0 {
		i -= len(m.BallotIdentifier)
		copy(dAtA[i:], m.BallotIdentifier)
		i = encodeVarintBallot(dAtA, i, uint64(len(m.BallotIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintBallot(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BallotListForHeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BallotListForHeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BallotListForHeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BallotsIndexList) > 0 {
		for iNdEx := len(m.BallotsIndexList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BallotsIndexList[iNdEx])
			copy(dAtA[i:], m.BallotsIndexList[iNdEx])
			i = encodeVarintBallot(dAtA, i, uint64(len(m.BallotsIndexList[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Height != 0 {
		i = encodeVarintBallot(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBallot(dAtA []byte, offset int, v uint64) int {
	offset -= sovBallot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Ballot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovBallot(uint64(l))
	}
	l = len(m.BallotIdentifier)
	if l > 0 {
		n += 1 + l + sovBallot(uint64(l))
	}
	if len(m.VoterList) > 0 {
		for _, s := range m.VoterList {
			l = len(s)
			n += 1 + l + sovBallot(uint64(l))
		}
	}
	if len(m.Votes) > 0 {
		l = 0
		for _, e := range m.Votes {
			l += sovBallot(uint64(e))
		}
		n += 1 + sovBallot(uint64(l)) + l
	}
	if m.ObservationType != 0 {
		n += 1 + sovBallot(uint64(m.ObservationType))
	}
	l = m.BallotThreshold.Size()
	n += 1 + l + sovBallot(uint64(l))
	if m.BallotStatus != 0 {
		n += 1 + sovBallot(uint64(m.BallotStatus))
	}
	if m.BallotCreationHeight != 0 {
		n += 1 + sovBallot(uint64(m.BallotCreationHeight))
	}
	return n
}

func (m *BallotListForHeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovBallot(uint64(m.Height))
	}
	if len(m.BallotsIndexList) > 0 {
		for _, s := range m.BallotsIndexList {
			l = len(s)
			n += 1 + l + sovBallot(uint64(l))
		}
	}
	return n
}

func sovBallot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBallot(x uint64) (n int) {
	return sovBallot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ballot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBallot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ballot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ballot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBallot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBallot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBallot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBallot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoterList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBallot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBallot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoterList = append(m.VoterList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v VoteType
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBallot
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= VoteType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Votes = append(m.Votes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBallot
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBallot
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBallot
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Votes) == 0 {
					m.Votes = make([]VoteType, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v VoteType
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBallot
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= VoteType(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Votes = append(m.Votes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservationType", wireType)
			}
			m.ObservationType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservationType |= ObservationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBallot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBallot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BallotThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotStatus", wireType)
			}
			m.BallotStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BallotStatus |= BallotStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotCreationHeight", wireType)
			}
			m.BallotCreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BallotCreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBallot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBallot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BallotListForHeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBallot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BallotListForHeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BallotListForHeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotsIndexList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBallot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBallot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotsIndexList = append(m.BallotsIndexList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBallot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBallot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBallot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBallot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBallot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBallot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBallot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBallot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBallot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBallot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBallot = fmt.Errorf("proto: unexpected end of group")
)
