// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/node_account.proto

package types

import (
	fmt "fmt"
	crypto "github.com/0xPellNetwork/aegis/pkg/crypto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// node status
type NodeStatus int32

const (
	// unknown node status
	NodeStatus_UNKNOWN NodeStatus = 0
	// whitelisted node status
	NodeStatus_WHITELISTED NodeStatus = 1
	// standby node status
	NodeStatus_STANDBY NodeStatus = 2
	// ready node status
	NodeStatus_READY NodeStatus = 3
	// active node status
	NodeStatus_ACTIVE NodeStatus = 4
	// disabled node status
	NodeStatus_DISABLED NodeStatus = 5
)

var NodeStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "WHITELISTED",
	2: "STANDBY",
	3: "READY",
	4: "ACTIVE",
	5: "DISABLED",
}

var NodeStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"WHITELISTED": 1,
	"STANDBY":     2,
	"READY":       3,
	"ACTIVE":      4,
	"DISABLED":    5,
}

func (x NodeStatus) String() string {
	return proto.EnumName(NodeStatus_name, int32(x))
}

func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a60af943940a815a, []int{0}
}

// node account
type NodeAccount struct {
	Operator       string            `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	GranteeAddress string            `protobuf:"bytes,2,opt,name=grantee_address,json=granteeAddress,proto3" json:"grantee_address,omitempty"`
	GranteePubkey  *crypto.PubKeySet `protobuf:"bytes,3,opt,name=grantee_pubkey,json=granteePubkey,proto3" json:"grantee_pubkey,omitempty"`
	NodeStatus     NodeStatus        `protobuf:"varint,4,opt,name=node_status,json=nodeStatus,proto3,enum=relayer.NodeStatus" json:"node_status,omitempty"`
}

func (m *NodeAccount) Reset()         { *m = NodeAccount{} }
func (m *NodeAccount) String() string { return proto.CompactTextString(m) }
func (*NodeAccount) ProtoMessage()    {}
func (*NodeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60af943940a815a, []int{0}
}
func (m *NodeAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAccount.Merge(m, src)
}
func (m *NodeAccount) XXX_Size() int {
	return m.Size()
}
func (m *NodeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAccount proto.InternalMessageInfo

func (m *NodeAccount) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *NodeAccount) GetGranteeAddress() string {
	if m != nil {
		return m.GranteeAddress
	}
	return ""
}

func (m *NodeAccount) GetGranteePubkey() *crypto.PubKeySet {
	if m != nil {
		return m.GranteePubkey
	}
	return nil
}

func (m *NodeAccount) GetNodeStatus() NodeStatus {
	if m != nil {
		return m.NodeStatus
	}
	return NodeStatus_UNKNOWN
}

func init() {
	proto.RegisterEnum("relayer.NodeStatus", NodeStatus_name, NodeStatus_value)
	proto.RegisterType((*NodeAccount)(nil), "relayer.NodeAccount")
}

func init() { proto.RegisterFile("relayer/node_account.proto", fileDescriptor_a60af943940a815a) }

var fileDescriptor_a60af943940a815a = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xcb, 0x8e, 0x9b, 0x30,
	0x14, 0x86, 0x71, 0xee, 0x31, 0x6d, 0x82, 0xdc, 0x56, 0x45, 0x2c, 0x50, 0xd4, 0x4d, 0xa3, 0x2e,
	0xa0, 0x4a, 0xbb, 0xec, 0x86, 0x14, 0xa4, 0xa0, 0x44, 0x34, 0x02, 0xda, 0x28, 0xdd, 0x44, 0x5c,
	0x2c, 0x1a, 0x91, 0x62, 0x64, 0x8c, 0x26, 0xbc, 0xc5, 0x3c, 0xc4, 0x2c, 0xe6, 0x49, 0x46, 0xb3,
	0xcc, 0x72, 0x96, 0xa3, 0xe4, 0x45, 0x46, 0x01, 0x92, 0x59, 0xf9, 0xf8, 0xfb, 0x7e, 0xd9, 0x3e,
	0x3e, 0x50, 0xa2, 0x78, 0xe7, 0x15, 0x98, 0xaa, 0x09, 0x09, 0xf1, 0xc6, 0x0b, 0x02, 0x92, 0x27,
	0x4c, 0x49, 0x29, 0x61, 0x04, 0x75, 0x6b, 0x27, 0xbd, 0x8f, 0x48, 0x44, 0x4a, 0xa6, 0x9e, 0xab,
	0x4a, 0x4b, 0x1f, 0xd3, 0x38, 0x52, 0x03, 0x5a, 0xa4, 0x8c, 0xd4, 0x4b, 0x25, 0x3e, 0x3d, 0x00,
	0xc8, 0x5b, 0x24, 0xc4, 0x5a, 0x75, 0x1a, 0x92, 0x60, 0x8f, 0xa4, 0x98, 0x7a, 0x8c, 0x50, 0x11,
	0x8c, 0xc0, 0xb8, 0x6f, 0x5f, 0xf7, 0xe8, 0x33, 0x1c, 0x46, 0xd4, 0x4b, 0x18, 0xc6, 0x1b, 0x2f,
	0x0c, 0x29, 0xce, 0x32, 0xb1, 0x51, 0x46, 0x06, 0x35, 0xd6, 0x2a, 0x8a, 0x7e, 0xc0, 0x0b, 0xd9,
	0xa4, 0xb9, 0x1f, 0xe3, 0x42, 0x6c, 0x8e, 0xc0, 0x98, 0x9f, 0x7c, 0x50, 0xd2, 0x38, 0x52, 0xea,
	0xfb, 0x97, 0xb9, 0x3f, 0xc7, 0x85, 0x83, 0x99, 0xfd, 0xb6, 0x0e, 0x2f, 0xcb, 0x2c, 0xfa, 0x0e,
	0xf9, 0xb2, 0xc1, 0x8c, 0x79, 0x2c, 0xcf, 0xc4, 0xd6, 0x08, 0x8c, 0x07, 0x93, 0x77, 0x4a, 0xdd,
	0xa0, 0x72, 0x7e, 0xad, 0x53, 0x2a, 0x1b, 0x26, 0xd7, 0xfa, 0x8b, 0x0f, 0xe1, 0xab, 0x41, 0x3c,
	0xec, 0xfe, 0xb6, 0xe6, 0xd6, 0xaf, 0x95, 0x25, 0x70, 0x68, 0x08, 0xf9, 0xd5, 0xcc, 0x74, 0x8d,
	0x85, 0xe9, 0xb8, 0x86, 0x2e, 0x80, 0xb3, 0x75, 0x5c, 0xcd, 0xd2, 0xa7, 0x6b, 0xa1, 0x81, 0xfa,
	0xb0, 0x6d, 0x1b, 0x9a, 0xbe, 0x16, 0x9a, 0x08, 0xc2, 0x8e, 0xf6, 0xd3, 0x35, 0xff, 0x18, 0x42,
	0x0b, 0xbd, 0x81, 0x3d, 0xdd, 0x74, 0xb4, 0xe9, 0xc2, 0xd0, 0x85, 0xb6, 0xd4, 0xba, 0xbf, 0x93,
	0xc1, 0x74, 0xf6, 0x78, 0x94, 0xc1, 0xe1, 0x28, 0x83, 0xe7, 0xa3, 0x0c, 0x6e, 0x4f, 0x32, 0x77,
	0x38, 0xc9, 0xdc, 0xd3, 0x49, 0xe6, 0xfe, 0x2a, 0xd1, 0x96, 0xfd, 0xcb, 0x7d, 0x25, 0x20, 0xff,
	0xd5, 0xaf, 0xfb, 0x25, 0xde, 0xed, 0x2c, 0xcc, 0x6e, 0x08, 0x8d, 0x55, 0x0f, 0x47, 0xdb, 0x4c,
	0xdd, 0xab, 0x97, 0xd9, 0xb1, 0x22, 0xc5, 0x99, 0xdf, 0x29, 0x7f, 0xff, 0xdb, 0x4b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xac, 0xfa, 0x99, 0x28, 0xd3, 0x01, 0x00, 0x00,
}

func (m *NodeAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NodeStatus != 0 {
		i = encodeVarintNodeAccount(dAtA, i, uint64(m.NodeStatus))
		i--
		dAtA[i] = 0x20
	}
	if m.GranteePubkey != nil {
		{
			size, err := m.GranteePubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNodeAccount(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.GranteeAddress) > 0 {
		i -= len(m.GranteeAddress)
		copy(dAtA[i:], m.GranteeAddress)
		i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.GranteeAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNodeAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovNodeAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	l = len(m.GranteeAddress)
	if l > 0 {
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	if m.GranteePubkey != nil {
		l = m.GranteePubkey.Size()
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	if m.NodeStatus != 0 {
		n += 1 + sovNodeAccount(uint64(m.NodeStatus))
	}
	return n
}

func sovNodeAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNodeAccount(x uint64) (n int) {
	return sovNodeAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GranteeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GranteeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GranteePubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GranteePubkey == nil {
				m.GranteePubkey = &crypto.PubKeySet{}
			}
			if err := m.GranteePubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeStatus", wireType)
			}
			m.NodeStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeStatus |= NodeStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodeAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodeAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNodeAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNodeAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNodeAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNodeAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodeAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNodeAccount = fmt.Errorf("proto: unexpected end of group")
)
