// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	chains "github.com/0xPellNetwork/aegis/pkg/chains"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Deprecated(v14):Moved into the authority module
type PolicyType int32

const (
	// group1 policy type
	PolicyType_GROUP1 PolicyType = 0
	// group2 policy type
	PolicyType_GROUP2 PolicyType = 1
)

var PolicyType_name = map[int32]string{
	0: "GROUP1",
	1: "GROUP2",
}

var PolicyType_value = map[string]int32{
	"GROUP1": 0,
	"GROUP2": 1,
}

func (x PolicyType) String() string {
	return proto.EnumName(PolicyType_name, int32(x))
}

func (PolicyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{0}
}

// ChainParamsList represents the list of chain parameters
type ChainParamsList struct {
	ChainParams []*ChainParams `protobuf:"bytes,1,rep,name=chain_params,json=chainParams,proto3" json:"chain_params,omitempty"`
}

func (m *ChainParamsList) Reset()         { *m = ChainParamsList{} }
func (m *ChainParamsList) String() string { return proto.CompactTextString(m) }
func (*ChainParamsList) ProtoMessage()    {}
func (*ChainParamsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{0}
}
func (m *ChainParamsList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainParamsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainParamsList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainParamsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainParamsList.Merge(m, src)
}
func (m *ChainParamsList) XXX_Size() int {
	return m.Size()
}
func (m *ChainParamsList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainParamsList.DiscardUnknown(m)
}

var xxx_messageInfo_ChainParamsList proto.InternalMessageInfo

func (m *ChainParamsList) GetChainParams() []*ChainParams {
	if m != nil {
		return m.ChainParams
	}
	return nil
}

// ChainParams represents the parameters of a chain
type ChainParams struct {
	ChainId                                  int64                       `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ConfirmationCount                        uint64                      `protobuf:"varint,2,opt,name=confirmation_count,json=confirmationCount,proto3" json:"confirmation_count,omitempty"`
	GasPriceTicker                           uint64                      `protobuf:"varint,3,opt,name=gas_price_ticker,json=gasPriceTicker,proto3" json:"gas_price_ticker,omitempty"`
	InTxTicker                               uint64                      `protobuf:"varint,4,opt,name=in_tx_ticker,json=inTxTicker,proto3" json:"in_tx_ticker,omitempty"`
	OutTxTicker                              uint64                      `protobuf:"varint,5,opt,name=out_tx_ticker,json=outTxTicker,proto3" json:"out_tx_ticker,omitempty"`
	OutboundTxScheduleInterval               int64                       `protobuf:"varint,6,opt,name=outbound_tx_schedule_interval,json=outboundTxScheduleInterval,proto3" json:"outbound_tx_schedule_interval,omitempty"`
	OutboundTxScheduleLookahead              int64                       `protobuf:"varint,7,opt,name=outbound_tx_schedule_lookahead,json=outboundTxScheduleLookahead,proto3" json:"outbound_tx_schedule_lookahead,omitempty"`
	BallotThreshold                          cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=ballot_threshold,json=ballotThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ballot_threshold"`
	MinObserverDelegation                    cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=min_observer_delegation,json=minObserverDelegation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_observer_delegation"`
	IsSupported                              bool                        `protobuf:"varint,10,opt,name=is_supported,json=isSupported,proto3" json:"is_supported,omitempty"`
	StrategyManagerContractAddress           string                      `protobuf:"bytes,11,opt,name=strategy_manager_contract_address,json=strategyManagerContractAddress,proto3" json:"strategy_manager_contract_address,omitempty"`
	DelegationManagerContractAddress         string                      `protobuf:"bytes,12,opt,name=delegation_manager_contract_address,json=delegationManagerContractAddress,proto3" json:"delegation_manager_contract_address,omitempty"`
	OmniOperatorSharesManagerContractAddress string                      `protobuf:"bytes,13,opt,name=omni_operator_shares_manager_contract_address,json=omniOperatorSharesManagerContractAddress,proto3" json:"omni_operator_shares_manager_contract_address,omitempty"`
	ConnectorContractAddress                 string                      `protobuf:"bytes,14,opt,name=connector_contract_address,json=connectorContractAddress,proto3" json:"connector_contract_address,omitempty"`
	StartBlockHeight                         uint64                      `protobuf:"varint,15,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	GasLimit                                 uint64                      `protobuf:"varint,16,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	WatchPellTokenTicker                     uint64                      `protobuf:"varint,17,opt,name=watch_pell_token_ticker,json=watchPellTokenTicker,proto3" json:"watch_pell_token_ticker,omitempty"`
	WatchGasTokenTicker                      uint64                      `protobuf:"varint,18,opt,name=watch_gas_token_ticker,json=watchGasTokenTicker,proto3" json:"watch_gas_token_ticker,omitempty"`
	PellTokenRechargeThreshold               cosmossdk_io_math.Int       `protobuf:"bytes,19,opt,name=pell_token_recharge_threshold,json=pellTokenRechargeThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"pell_token_recharge_threshold"`
	GasTokenRechargeThreshold                cosmossdk_io_math.Int       `protobuf:"bytes,20,opt,name=gas_token_recharge_threshold,json=gasTokenRechargeThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"gas_token_recharge_threshold"`
	PellTokenRechargeAmount                  cosmossdk_io_math.Int       `protobuf:"bytes,21,opt,name=pell_token_recharge_amount,json=pellTokenRechargeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"pell_token_recharge_amount"`
	GasTokenRechargeAmount                   cosmossdk_io_math.Int       `protobuf:"bytes,22,opt,name=gas_token_recharge_amount,json=gasTokenRechargeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"gas_token_recharge_amount"`
	GatewayEvmContractAddress                string                      `protobuf:"bytes,23,opt,name=gateway_evm_contract_address,json=gatewayEvmContractAddress,proto3" json:"gateway_evm_contract_address,omitempty"`
	PellTokenContractAddress                 string                      `protobuf:"bytes,24,opt,name=pell_token_contract_address,json=pellTokenContractAddress,proto3" json:"pell_token_contract_address,omitempty"`
	GasSwapContractAddress                   string                      `protobuf:"bytes,25,opt,name=gas_swap_contract_address,json=gasSwapContractAddress,proto3" json:"gas_swap_contract_address,omitempty"`
	PellTokenPostInterval                    uint64                      `protobuf:"varint,26,opt,name=pell_token_post_interval,json=pellTokenPostInterval,proto3" json:"pell_token_post_interval,omitempty"`
	GasTokenPostInterval                     uint64                      `protobuf:"varint,27,opt,name=gas_token_post_interval,json=gasTokenPostInterval,proto3" json:"gas_token_post_interval,omitempty"`
	PellTokenRechargeEnabled                 bool                        `protobuf:"varint,28,opt,name=pell_token_recharge_enabled,json=pellTokenRechargeEnabled,proto3" json:"pell_token_recharge_enabled,omitempty"`
	GasTokenRechargeEnabled                  bool                        `protobuf:"varint,29,opt,name=gas_token_recharge_enabled,json=gasTokenRechargeEnabled,proto3" json:"gas_token_recharge_enabled,omitempty"`
	ChainRegistryInteractorContractAddress   string                      `protobuf:"bytes,30,opt,name=chain_registry_interactor_contract_address,json=chainRegistryInteractorContractAddress,proto3" json:"chain_registry_interactor_contract_address,omitempty"`
}

func (m *ChainParams) Reset()         { *m = ChainParams{} }
func (m *ChainParams) String() string { return proto.CompactTextString(m) }
func (*ChainParams) ProtoMessage()    {}
func (*ChainParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{1}
}
func (m *ChainParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainParams.Merge(m, src)
}
func (m *ChainParams) XXX_Size() int {
	return m.Size()
}
func (m *ChainParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChainParams proto.InternalMessageInfo

func (m *ChainParams) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ChainParams) GetConfirmationCount() uint64 {
	if m != nil {
		return m.ConfirmationCount
	}
	return 0
}

func (m *ChainParams) GetGasPriceTicker() uint64 {
	if m != nil {
		return m.GasPriceTicker
	}
	return 0
}

func (m *ChainParams) GetInTxTicker() uint64 {
	if m != nil {
		return m.InTxTicker
	}
	return 0
}

func (m *ChainParams) GetOutTxTicker() uint64 {
	if m != nil {
		return m.OutTxTicker
	}
	return 0
}

func (m *ChainParams) GetOutboundTxScheduleInterval() int64 {
	if m != nil {
		return m.OutboundTxScheduleInterval
	}
	return 0
}

func (m *ChainParams) GetOutboundTxScheduleLookahead() int64 {
	if m != nil {
		return m.OutboundTxScheduleLookahead
	}
	return 0
}

func (m *ChainParams) GetIsSupported() bool {
	if m != nil {
		return m.IsSupported
	}
	return false
}

func (m *ChainParams) GetStrategyManagerContractAddress() string {
	if m != nil {
		return m.StrategyManagerContractAddress
	}
	return ""
}

func (m *ChainParams) GetDelegationManagerContractAddress() string {
	if m != nil {
		return m.DelegationManagerContractAddress
	}
	return ""
}

func (m *ChainParams) GetOmniOperatorSharesManagerContractAddress() string {
	if m != nil {
		return m.OmniOperatorSharesManagerContractAddress
	}
	return ""
}

func (m *ChainParams) GetConnectorContractAddress() string {
	if m != nil {
		return m.ConnectorContractAddress
	}
	return ""
}

func (m *ChainParams) GetStartBlockHeight() uint64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

func (m *ChainParams) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ChainParams) GetWatchPellTokenTicker() uint64 {
	if m != nil {
		return m.WatchPellTokenTicker
	}
	return 0
}

func (m *ChainParams) GetWatchGasTokenTicker() uint64 {
	if m != nil {
		return m.WatchGasTokenTicker
	}
	return 0
}

func (m *ChainParams) GetGatewayEvmContractAddress() string {
	if m != nil {
		return m.GatewayEvmContractAddress
	}
	return ""
}

func (m *ChainParams) GetPellTokenContractAddress() string {
	if m != nil {
		return m.PellTokenContractAddress
	}
	return ""
}

func (m *ChainParams) GetGasSwapContractAddress() string {
	if m != nil {
		return m.GasSwapContractAddress
	}
	return ""
}

func (m *ChainParams) GetPellTokenPostInterval() uint64 {
	if m != nil {
		return m.PellTokenPostInterval
	}
	return 0
}

func (m *ChainParams) GetGasTokenPostInterval() uint64 {
	if m != nil {
		return m.GasTokenPostInterval
	}
	return 0
}

func (m *ChainParams) GetPellTokenRechargeEnabled() bool {
	if m != nil {
		return m.PellTokenRechargeEnabled
	}
	return false
}

func (m *ChainParams) GetGasTokenRechargeEnabled() bool {
	if m != nil {
		return m.GasTokenRechargeEnabled
	}
	return false
}

func (m *ChainParams) GetChainRegistryInteractorContractAddress() string {
	if m != nil {
		return m.ChainRegistryInteractorContractAddress
	}
	return ""
}

// Deprecated(v13): Use ChainParamsList
type RelayerParams struct {
	Chain                *chains.Chain               `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	BallotThreshold      cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=ballot_threshold,json=ballotThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ballot_threshold"`
	MinRelayerDelegation cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=min_relayer_delegation,json=minRelayerDelegation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_relayer_delegation"`
	IsSupported          bool                        `protobuf:"varint,5,opt,name=is_supported,json=isSupported,proto3" json:"is_supported,omitempty"`
}

func (m *RelayerParams) Reset()         { *m = RelayerParams{} }
func (m *RelayerParams) String() string { return proto.CompactTextString(m) }
func (*RelayerParams) ProtoMessage()    {}
func (*RelayerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{2}
}
func (m *RelayerParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayerParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerParams.Merge(m, src)
}
func (m *RelayerParams) XXX_Size() int {
	return m.Size()
}
func (m *RelayerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerParams.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerParams proto.InternalMessageInfo

func (m *RelayerParams) GetChain() *chains.Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *RelayerParams) GetIsSupported() bool {
	if m != nil {
		return m.IsSupported
	}
	return false
}

// Deprecated(v14):Moved into the authority module
type AdminPolicy struct {
	PolicyType PolicyType `protobuf:"varint,1,opt,name=policy_type,json=policyType,proto3,enum=relayer.PolicyType" json:"policy_type,omitempty"`
	Address    string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AdminPolicy) Reset()         { *m = AdminPolicy{} }
func (m *AdminPolicy) String() string { return proto.CompactTextString(m) }
func (*AdminPolicy) ProtoMessage()    {}
func (*AdminPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{3}
}
func (m *AdminPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminPolicy.Merge(m, src)
}
func (m *AdminPolicy) XXX_Size() int {
	return m.Size()
}
func (m *AdminPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_AdminPolicy proto.InternalMessageInfo

func (m *AdminPolicy) GetPolicyType() PolicyType {
	if m != nil {
		return m.PolicyType
	}
	return PolicyType_GROUP1
}

func (m *AdminPolicy) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Params defines the parameters for the module.
type Params struct {
	// Deprecated(v13): Use ChainParamsList
	ObserverParams []*RelayerParams `protobuf:"bytes,1,rep,name=observer_params,json=observerParams,proto3" json:"observer_params,omitempty"`
	// Deprecated(v14):Moved into the authority module
	AdminPolicy          []*AdminPolicy `protobuf:"bytes,2,rep,name=admin_policy,json=adminPolicy,proto3" json:"admin_policy,omitempty"`
	BallotMaturityBlocks int64          `protobuf:"varint,3,opt,name=ballot_maturity_blocks,json=ballotMaturityBlocks,proto3" json:"ballot_maturity_blocks,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccba6a72763fc2ad, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetObserverParams() []*RelayerParams {
	if m != nil {
		return m.ObserverParams
	}
	return nil
}

func (m *Params) GetAdminPolicy() []*AdminPolicy {
	if m != nil {
		return m.AdminPolicy
	}
	return nil
}

func (m *Params) GetBallotMaturityBlocks() int64 {
	if m != nil {
		return m.BallotMaturityBlocks
	}
	return 0
}

func init() {
	proto.RegisterEnum("relayer.PolicyType", PolicyType_name, PolicyType_value)
	proto.RegisterType((*ChainParamsList)(nil), "relayer.ChainParamsList")
	proto.RegisterType((*ChainParams)(nil), "relayer.ChainParams")
	proto.RegisterType((*RelayerParams)(nil), "relayer.RelayerParams")
	proto.RegisterType((*AdminPolicy)(nil), "relayer.AdminPolicy")
	proto.RegisterType((*Params)(nil), "relayer.Params")
}

func init() { proto.RegisterFile("relayer/params.proto", fileDescriptor_ccba6a72763fc2ad) }

var fileDescriptor_ccba6a72763fc2ad = []byte{
	// 1167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x49, 0x6f, 0xdb, 0x46,
	0x14, 0x16, 0xbd, 0xfb, 0xc9, 0x8b, 0x4c, 0xcb, 0x12, 0x2d, 0xc7, 0xb2, 0xa2, 0x00, 0xad, 0x60,
	0x34, 0x52, 0xeb, 0x34, 0x30, 0xba, 0x21, 0xb0, 0x9d, 0x20, 0x71, 0x61, 0xc7, 0x02, 0xad, 0x02,
	0xad, 0x8b, 0x96, 0x1d, 0x91, 0x53, 0x72, 0x20, 0x92, 0x43, 0xcc, 0x8c, 0x6c, 0xeb, 0x0f, 0xf4,
	0xd0, 0x53, 0x8f, 0x3d, 0xf6, 0xd0, 0x43, 0x7f, 0x45, 0xcf, 0x39, 0xe6, 0x58, 0xf4, 0x10, 0x14,
	0xf6, 0x1f, 0x29, 0x38, 0x5c, 0xb4, 0xba, 0x30, 0xd0, 0x93, 0x38, 0xf3, 0xbe, 0xef, 0x9b, 0xb7,
	0x69, 0xde, 0x40, 0x9e, 0x61, 0x17, 0xf5, 0x30, 0x6b, 0x04, 0x88, 0x21, 0x8f, 0xd7, 0x03, 0x46,
	0x05, 0x55, 0xe7, 0xe3, 0xdd, 0x52, 0xde, 0xa6, 0x36, 0x95, 0x7b, 0x8d, 0xf0, 0x2b, 0x32, 0x97,
	0x8a, 0x41, 0xc7, 0x6e, 0x98, 0x0e, 0x22, 0x3e, 0x8f, 0x7f, 0x22, 0x43, 0xf5, 0x4b, 0x58, 0x3d,
	0x0a, 0xd7, 0x4d, 0x29, 0x76, 0x42, 0xb8, 0x50, 0xf7, 0x61, 0x49, 0x42, 0x8c, 0xe8, 0x00, 0x4d,
	0xa9, 0x4c, 0xd7, 0xb2, 0x7b, 0xf9, 0x7a, 0x7c, 0x42, 0x7d, 0x00, 0xaf, 0x67, 0xcd, 0xfe, 0xa2,
	0xfa, 0xf3, 0x2a, 0x64, 0x07, 0x8c, 0xea, 0x26, 0x2c, 0x44, 0x42, 0xc4, 0xd2, 0x94, 0x8a, 0x52,
	0x9b, 0xd6, 0xe7, 0xe5, 0xfa, 0xd8, 0x52, 0x1f, 0x83, 0x6a, 0x52, 0xff, 0x47, 0xc2, 0x3c, 0x24,
	0x08, 0xf5, 0x0d, 0x93, 0x76, 0x7d, 0xa1, 0x4d, 0x55, 0x94, 0xda, 0x8c, 0xbe, 0x36, 0x68, 0x39,
	0x0a, 0x0d, 0x6a, 0x0d, 0x72, 0x36, 0xe2, 0x46, 0xc0, 0x88, 0x89, 0x0d, 0x41, 0xcc, 0x0e, 0x66,
	0xda, 0xb4, 0x04, 0xaf, 0xd8, 0x88, 0x37, 0xc3, 0xed, 0x96, 0xdc, 0x55, 0x2b, 0xb0, 0x44, 0x7c,
	0x43, 0x5c, 0x27, 0xa8, 0x19, 0x89, 0x02, 0xe2, 0xb7, 0xae, 0x63, 0x44, 0x15, 0x96, 0x69, 0x57,
	0x0c, 0x40, 0x66, 0x25, 0x24, 0x4b, 0xbb, 0x22, 0xc5, 0x1c, 0xc0, 0x36, 0xed, 0x8a, 0x36, 0xed,
	0xfa, 0x56, 0x08, 0xe4, 0xa6, 0x83, 0xad, 0xae, 0x8b, 0x0d, 0xe2, 0x0b, 0xcc, 0x2e, 0x91, 0xab,
	0xcd, 0xc9, 0x70, 0x4a, 0x09, 0xa8, 0x75, 0x7d, 0x1e, 0x43, 0x8e, 0x63, 0x84, 0x7a, 0x04, 0xe5,
	0x89, 0x12, 0x2e, 0xa5, 0x1d, 0xe4, 0x60, 0x64, 0x69, 0xf3, 0x52, 0x63, 0x6b, 0x5c, 0xe3, 0x24,
	0x81, 0xa8, 0xaf, 0x21, 0xd7, 0x46, 0xae, 0x4b, 0x85, 0x21, 0x1c, 0x86, 0xb9, 0x43, 0x5d, 0x4b,
	0x5b, 0xa8, 0x28, 0xb5, 0xc5, 0xc3, 0x47, 0x6f, 0xde, 0xed, 0x64, 0xfe, 0x7e, 0xb7, 0xb3, 0x65,
	0x52, 0xee, 0x51, 0xce, 0xad, 0x4e, 0x9d, 0xd0, 0x86, 0x87, 0x84, 0x53, 0x3f, 0xc1, 0x36, 0x32,
	0x7b, 0xcf, 0xb1, 0xa9, 0xaf, 0x46, 0xe4, 0x56, 0xc2, 0x55, 0xbf, 0x85, 0xa2, 0x47, 0x7c, 0x83,
	0xb6, 0x39, 0x66, 0x97, 0x98, 0x19, 0x16, 0x76, 0xb1, 0x2d, 0xf3, 0xac, 0x2d, 0xde, 0x5f, 0x76,
	0xc3, 0x23, 0xfe, 0x59, 0x2c, 0xf1, 0x3c, 0x55, 0x50, 0x1f, 0xc2, 0x12, 0xe1, 0x06, 0xef, 0x06,
	0x01, 0x65, 0x02, 0x5b, 0x1a, 0x54, 0x94, 0xda, 0x82, 0x9e, 0x25, 0xfc, 0x3c, 0xd9, 0x52, 0x8f,
	0xe1, 0x21, 0x17, 0x0c, 0x09, 0x6c, 0xf7, 0x0c, 0x0f, 0xf9, 0xc8, 0xc6, 0xcc, 0x30, 0xa9, 0x2f,
	0x18, 0x32, 0x85, 0x81, 0x2c, 0x8b, 0x61, 0xce, 0xb5, 0x6c, 0xe8, 0x89, 0x5e, 0x4e, 0x80, 0xa7,
	0x11, 0xee, 0x28, 0x86, 0x1d, 0x44, 0x28, 0xf5, 0x14, 0x1e, 0xf5, 0xbd, 0xbf, 0x5b, 0x6c, 0x49,
	0x8a, 0x55, 0xfa, 0xd0, 0x3b, 0xe4, 0x0c, 0x78, 0x4c, 0x3d, 0x9f, 0x18, 0x34, 0xc0, 0x0c, 0x09,
	0xca, 0x0c, 0xee, 0x20, 0x86, 0xf9, 0xdd, 0xc2, 0xcb, 0x52, 0xb8, 0x16, 0x92, 0xce, 0x62, 0xce,
	0xb9, 0xa4, 0xdc, 0x71, 0xc0, 0xe7, 0x50, 0x32, 0xa9, 0xef, 0x63, 0x33, 0x14, 0x1f, 0x53, 0x5b,
	0x91, 0x6a, 0x5a, 0x8a, 0x18, 0x65, 0x7f, 0x00, 0x2a, 0x17, 0x88, 0x09, 0xa3, 0xed, 0x52, 0xb3,
	0x63, 0x38, 0x98, 0xd8, 0x8e, 0xd0, 0x56, 0x65, 0xe7, 0xe6, 0xa4, 0xe5, 0x30, 0x34, 0xbc, 0x92,
	0xfb, 0xea, 0x16, 0x2c, 0x86, 0x7f, 0x17, 0x97, 0x78, 0x44, 0x68, 0x39, 0x09, 0x5a, 0xb0, 0x11,
	0x3f, 0x09, 0xd7, 0xea, 0x53, 0x28, 0x5e, 0x21, 0x61, 0x3a, 0x46, 0x80, 0x5d, 0xd7, 0x10, 0xb4,
	0x83, 0xfd, 0xe4, 0x9f, 0xb0, 0x26, 0xa1, 0x79, 0x69, 0x6e, 0x62, 0xd7, 0x6d, 0x85, 0xc6, 0xf8,
	0x2f, 0xf1, 0x04, 0x0a, 0x11, 0x2d, 0x54, 0x1e, 0x62, 0xa9, 0x92, 0xb5, 0x2e, 0xad, 0x2f, 0x11,
	0x1f, 0x24, 0xfd, 0x00, 0xdb, 0x03, 0xa7, 0x30, 0x6c, 0x3a, 0x88, 0xd9, 0x78, 0xa0, 0x99, 0xd7,
	0x65, 0xd7, 0x6d, 0xc7, 0x5d, 0xb7, 0x31, 0xde, 0x75, 0xc7, 0xbe, 0xd0, 0x4b, 0x41, 0xe2, 0x8b,
	0x1e, 0x2b, 0xf4, 0x3b, 0xfa, 0x7b, 0x78, 0xd0, 0x77, 0x68, 0xc2, 0x01, 0xf9, 0xfb, 0x1c, 0xb0,
	0x69, 0xc7, 0x6e, 0x8f, 0xeb, 0x5f, 0x40, 0x69, 0x52, 0x04, 0xc8, 0x93, 0x17, 0xd6, 0xc6, 0x7d,
	0xd4, 0x8b, 0x63, 0xee, 0x1f, 0x48, 0xb6, 0xfa, 0x35, 0x6c, 0x4e, 0xf0, 0x3d, 0x96, 0x2e, 0xdc,
	0x47, 0xba, 0x30, 0xea, 0x78, 0xac, 0xfc, 0x2c, 0xcc, 0x8a, 0xc0, 0x57, 0xa8, 0x67, 0xe0, 0x4b,
	0x6f, 0xbc, 0xdd, 0x8a, 0xb2, 0xdd, 0x36, 0x63, 0xcc, 0x8b, 0x4b, 0x6f, 0xb4, 0xdf, 0xbe, 0x80,
	0xad, 0x81, 0xb0, 0xc7, 0xf8, 0x5a, 0xd4, 0xae, 0x69, 0x60, 0xa3, 0xf4, 0x4f, 0xa2, 0xc8, 0xf8,
	0x15, 0x0a, 0xc6, 0xc9, 0x9b, 0x92, 0x1c, 0xba, 0x7e, 0x7e, 0x85, 0x82, 0x51, 0xea, 0x3e, 0x68,
	0x03, 0x27, 0x07, 0x94, 0x8b, 0xfe, 0xad, 0x5b, 0x92, 0x9d, 0xb6, 0x91, 0x1e, 0xdb, 0xa4, 0x5c,
	0xa4, 0x17, 0xee, 0x53, 0x28, 0xf6, 0xb3, 0x39, 0xcc, 0xdb, 0x8a, 0xfa, 0x3a, 0x49, 0xd6, 0x10,
	0x6d, 0x38, 0xd2, 0xb4, 0x0a, 0xd8, 0x47, 0x6d, 0x17, 0x5b, 0xda, 0x03, 0x79, 0x89, 0x69, 0x63,
	0x25, 0x7c, 0x11, 0xd9, 0xd5, 0xcf, 0xa0, 0x34, 0xa1, 0x86, 0x09, 0x7b, 0x5b, 0xb2, 0x8b, 0xa3,
	0x55, 0x4a, 0xc8, 0x17, 0xb0, 0x1b, 0x0d, 0x48, 0x86, 0x6d, 0xc2, 0x05, 0xeb, 0x45, 0x2e, 0xa3,
	0xc9, 0x77, 0x44, 0x59, 0xe6, 0xed, 0x3d, 0xc9, 0xd0, 0x63, 0xc2, 0x71, 0x8a, 0x1f, 0xc9, 0x63,
	0xf5, 0xa7, 0x29, 0x58, 0xd6, 0xa3, 0x89, 0x1d, 0x8f, 0xe3, 0xf7, 0x61, 0x56, 0x72, 0xe5, 0x2c,
	0xce, 0xee, 0xad, 0xd5, 0x83, 0x8e, 0x5d, 0x8f, 0x1f, 0x03, 0x72, 0x6c, 0xeb, 0x91, 0x7d, 0xe2,
	0xd4, 0x99, 0xfe, 0x1f, 0x53, 0xe7, 0x1b, 0x28, 0x78, 0x32, 0x48, 0xe9, 0xcd, 0xe0, 0xd0, 0x99,
	0xb9, 0xbf, 0x6a, 0xde, 0x0b, 0xa3, 0x96, 0x0a, 0xff, 0x31, 0x73, 0x66, 0xc7, 0x66, 0x4e, 0xf5,
	0x3b, 0xc8, 0x1e, 0x58, 0x1e, 0xf1, 0x9b, 0xd4, 0x25, 0x66, 0x4f, 0xfd, 0x18, 0xb2, 0x81, 0xfc,
	0x32, 0x44, 0x2f, 0xc0, 0x32, 0x17, 0x2b, 0x7b, 0xeb, 0xe9, 0xe3, 0x26, 0x42, 0xb5, 0x7a, 0x01,
	0xd6, 0x21, 0x48, 0xbf, 0x55, 0x0d, 0xe6, 0x93, 0x32, 0x4c, 0xc9, 0x32, 0x24, 0xcb, 0xea, 0x9f,
	0x0a, 0xcc, 0xc5, 0x09, 0x7e, 0x06, 0xab, 0xe9, 0x64, 0x1d, 0x7a, 0x3b, 0x15, 0x52, 0xf9, 0xa1,
	0x8a, 0xe8, 0x2b, 0x09, 0x3c, 0x16, 0xd8, 0x87, 0x25, 0x14, 0xba, 0x6a, 0x44, 0x27, 0x6b, 0x53,
	0x23, 0x2f, 0xaf, 0x81, 0x38, 0xf4, 0x2c, 0x1a, 0x0a, 0xaa, 0x10, 0x57, 0xcc, 0x43, 0xa2, 0xcb,
	0x88, 0xe8, 0x45, 0x83, 0x82, 0xcb, 0xba, 0x4d, 0xeb, 0xf9, 0xc8, 0x7a, 0x1a, 0x1b, 0xe5, 0xac,
	0xe0, 0x9f, 0xce, 0xfc, 0xfa, 0xdb, 0x4e, 0x66, 0x77, 0x17, 0xa0, 0x1f, 0xb4, 0x0a, 0x30, 0xf7,
	0x52, 0x3f, 0xfb, 0xaa, 0xf9, 0x51, 0x2e, 0x93, 0x7e, 0xef, 0xe5, 0x94, 0xd2, 0xcc, 0x1f, 0xbf,
	0x97, 0x95, 0xc3, 0x57, 0x6f, 0x6e, 0xca, 0xca, 0xdb, 0x9b, 0xb2, 0xf2, 0xcf, 0x4d, 0x59, 0xf9,
	0xe5, 0xb6, 0x9c, 0x79, 0x7b, 0x5b, 0xce, 0xfc, 0x75, 0x5b, 0xce, 0x5c, 0xd4, 0x6d, 0x22, 0x9c,
	0x6e, 0xbb, 0x6e, 0x52, 0xaf, 0xf1, 0xe1, 0x75, 0x38, 0x3c, 0x5e, 0x63, 0x71, 0x45, 0x59, 0xa7,
	0x81, 0xc2, 0x56, 0x6d, 0x5c, 0x37, 0x92, 0x67, 0x6b, 0x98, 0x76, 0xde, 0x9e, 0x93, 0xcf, 0xcf,
	0x27, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x50, 0x7f, 0xcf, 0xd2, 0xce, 0x0a, 0x00, 0x00,
}

func (m *ChainParamsList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainParamsList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainParamsList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainParams) > 0 {
		for iNdEx := len(m.ChainParams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChainParams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ChainParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainRegistryInteractorContractAddress) > 0 {
		i -= len(m.ChainRegistryInteractorContractAddress)
		copy(dAtA[i:], m.ChainRegistryInteractorContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ChainRegistryInteractorContractAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf2
	}
	if m.GasTokenRechargeEnabled {
		i--
		if m.GasTokenRechargeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe8
	}
	if m.PellTokenRechargeEnabled {
		i--
		if m.PellTokenRechargeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.GasTokenPostInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.GasTokenPostInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.PellTokenPostInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PellTokenPostInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if len(m.GasSwapContractAddress) > 0 {
		i -= len(m.GasSwapContractAddress)
		copy(dAtA[i:], m.GasSwapContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.GasSwapContractAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if len(m.PellTokenContractAddress) > 0 {
		i -= len(m.PellTokenContractAddress)
		copy(dAtA[i:], m.PellTokenContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PellTokenContractAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.GatewayEvmContractAddress) > 0 {
		i -= len(m.GatewayEvmContractAddress)
		copy(dAtA[i:], m.GatewayEvmContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.GatewayEvmContractAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	{
		size := m.GasTokenRechargeAmount.Size()
		i -= size
		if _, err := m.GasTokenRechargeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xb2
	{
		size := m.PellTokenRechargeAmount.Size()
		i -= size
		if _, err := m.PellTokenRechargeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xaa
	{
		size := m.GasTokenRechargeThreshold.Size()
		i -= size
		if _, err := m.GasTokenRechargeThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xa2
	{
		size := m.PellTokenRechargeThreshold.Size()
		i -= size
		if _, err := m.PellTokenRechargeThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	if m.WatchGasTokenTicker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WatchGasTokenTicker))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.WatchPellTokenTicker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WatchPellTokenTicker))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.GasLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.StartBlockHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StartBlockHeight))
		i--
		dAtA[i] = 0x78
	}
	if len(m.ConnectorContractAddress) > 0 {
		i -= len(m.ConnectorContractAddress)
		copy(dAtA[i:], m.ConnectorContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ConnectorContractAddress)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.OmniOperatorSharesManagerContractAddress) > 0 {
		i -= len(m.OmniOperatorSharesManagerContractAddress)
		copy(dAtA[i:], m.OmniOperatorSharesManagerContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OmniOperatorSharesManagerContractAddress)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.DelegationManagerContractAddress) > 0 {
		i -= len(m.DelegationManagerContractAddress)
		copy(dAtA[i:], m.DelegationManagerContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DelegationManagerContractAddress)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.StrategyManagerContractAddress) > 0 {
		i -= len(m.StrategyManagerContractAddress)
		copy(dAtA[i:], m.StrategyManagerContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.StrategyManagerContractAddress)))
		i--
		dAtA[i] = 0x5a
	}
	if m.IsSupported {
		i--
		if m.IsSupported {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.MinObserverDelegation.Size()
		i -= size
		if _, err := m.MinObserverDelegation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.BallotThreshold.Size()
		i -= size
		if _, err := m.BallotThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.OutboundTxScheduleLookahead != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OutboundTxScheduleLookahead))
		i--
		dAtA[i] = 0x38
	}
	if m.OutboundTxScheduleInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OutboundTxScheduleInterval))
		i--
		dAtA[i] = 0x30
	}
	if m.OutTxTicker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OutTxTicker))
		i--
		dAtA[i] = 0x28
	}
	if m.InTxTicker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.InTxTicker))
		i--
		dAtA[i] = 0x20
	}
	if m.GasPriceTicker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.GasPriceTicker))
		i--
		dAtA[i] = 0x18
	}
	if m.ConfirmationCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ConfirmationCount))
		i--
		dAtA[i] = 0x10
	}
	if m.ChainId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RelayerParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayerParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayerParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsSupported {
		i--
		if m.IsSupported {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MinRelayerDelegation.Size()
		i -= size
		if _, err := m.MinRelayerDelegation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BallotThreshold.Size()
		i -= size
		if _, err := m.BallotThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Chain != nil {
		{
			size, err := m.Chain.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AdminPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.PolicyType != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PolicyType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BallotMaturityBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BallotMaturityBlocks))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AdminPolicy) > 0 {
		for iNdEx := len(m.AdminPolicy) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AdminPolicy[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ObserverParams) > 0 {
		for iNdEx := len(m.ObserverParams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ObserverParams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainParamsList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ChainParams) > 0 {
		for _, e := range m.ChainParams {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *ChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovParams(uint64(m.ChainId))
	}
	if m.ConfirmationCount != 0 {
		n += 1 + sovParams(uint64(m.ConfirmationCount))
	}
	if m.GasPriceTicker != 0 {
		n += 1 + sovParams(uint64(m.GasPriceTicker))
	}
	if m.InTxTicker != 0 {
		n += 1 + sovParams(uint64(m.InTxTicker))
	}
	if m.OutTxTicker != 0 {
		n += 1 + sovParams(uint64(m.OutTxTicker))
	}
	if m.OutboundTxScheduleInterval != 0 {
		n += 1 + sovParams(uint64(m.OutboundTxScheduleInterval))
	}
	if m.OutboundTxScheduleLookahead != 0 {
		n += 1 + sovParams(uint64(m.OutboundTxScheduleLookahead))
	}
	l = m.BallotThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinObserverDelegation.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.IsSupported {
		n += 2
	}
	l = len(m.StrategyManagerContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DelegationManagerContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OmniOperatorSharesManagerContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ConnectorContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.StartBlockHeight != 0 {
		n += 1 + sovParams(uint64(m.StartBlockHeight))
	}
	if m.GasLimit != 0 {
		n += 2 + sovParams(uint64(m.GasLimit))
	}
	if m.WatchPellTokenTicker != 0 {
		n += 2 + sovParams(uint64(m.WatchPellTokenTicker))
	}
	if m.WatchGasTokenTicker != 0 {
		n += 2 + sovParams(uint64(m.WatchGasTokenTicker))
	}
	l = m.PellTokenRechargeThreshold.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.GasTokenRechargeThreshold.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.PellTokenRechargeAmount.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.GasTokenRechargeAmount.Size()
	n += 2 + l + sovParams(uint64(l))
	l = len(m.GatewayEvmContractAddress)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	l = len(m.PellTokenContractAddress)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	l = len(m.GasSwapContractAddress)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.PellTokenPostInterval != 0 {
		n += 2 + sovParams(uint64(m.PellTokenPostInterval))
	}
	if m.GasTokenPostInterval != 0 {
		n += 2 + sovParams(uint64(m.GasTokenPostInterval))
	}
	if m.PellTokenRechargeEnabled {
		n += 3
	}
	if m.GasTokenRechargeEnabled {
		n += 3
	}
	l = len(m.ChainRegistryInteractorContractAddress)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	return n
}

func (m *RelayerParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Chain != nil {
		l = m.Chain.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.BallotThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinRelayerDelegation.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.IsSupported {
		n += 2
	}
	return n
}

func (m *AdminPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PolicyType != 0 {
		n += 1 + sovParams(uint64(m.PolicyType))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ObserverParams) > 0 {
		for _, e := range m.ObserverParams {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.AdminPolicy) > 0 {
		for _, e := range m.AdminPolicy {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.BallotMaturityBlocks != 0 {
		n += 1 + sovParams(uint64(m.BallotMaturityBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainParamsList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainParamsList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainParamsList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainParams = append(m.ChainParams, &ChainParams{})
			if err := m.ChainParams[len(m.ChainParams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfirmationCount", wireType)
			}
			m.ConfirmationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfirmationCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPriceTicker", wireType)
			}
			m.GasPriceTicker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasPriceTicker |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxTicker", wireType)
			}
			m.InTxTicker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InTxTicker |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutTxTicker", wireType)
			}
			m.OutTxTicker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutTxTicker |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundTxScheduleInterval", wireType)
			}
			m.OutboundTxScheduleInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutboundTxScheduleInterval |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundTxScheduleLookahead", wireType)
			}
			m.OutboundTxScheduleLookahead = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutboundTxScheduleLookahead |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BallotThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinObserverDelegation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinObserverDelegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSupported", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSupported = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategyManagerContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StrategyManagerContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationManagerContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationManagerContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OmniOperatorSharesManagerContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OmniOperatorSharesManagerContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectorContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHeight", wireType)
			}
			m.StartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WatchPellTokenTicker", wireType)
			}
			m.WatchPellTokenTicker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WatchPellTokenTicker |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WatchGasTokenTicker", wireType)
			}
			m.WatchGasTokenTicker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WatchGasTokenTicker |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellTokenRechargeThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PellTokenRechargeThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasTokenRechargeThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasTokenRechargeThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellTokenRechargeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PellTokenRechargeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasTokenRechargeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasTokenRechargeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayEvmContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayEvmContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellTokenContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PellTokenContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasSwapContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasSwapContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellTokenPostInterval", wireType)
			}
			m.PellTokenPostInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PellTokenPostInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasTokenPostInterval", wireType)
			}
			m.GasTokenPostInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasTokenPostInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PellTokenRechargeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PellTokenRechargeEnabled = bool(v != 0)
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasTokenRechargeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GasTokenRechargeEnabled = bool(v != 0)
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainRegistryInteractorContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainRegistryInteractorContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayerParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayerParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayerParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Chain == nil {
				m.Chain = &chains.Chain{}
			}
			if err := m.Chain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BallotThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRelayerDelegation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinRelayerDelegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSupported", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSupported = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyType", wireType)
			}
			m.PolicyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyType |= PolicyType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObserverParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObserverParams = append(m.ObserverParams, &RelayerParams{})
			if err := m.ObserverParams[len(m.ObserverParams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdminPolicy = append(m.AdminPolicy, &AdminPolicy{})
			if err := m.AdminPolicy[len(m.AdminPolicy)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotMaturityBlocks", wireType)
			}
			m.BallotMaturityBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BallotMaturityBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
