// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/relayer.proto

package types

import (
	fmt "fmt"
	chains "github.com/0xPellNetwork/aegis/pkg/chains"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// observation type
type ObservationType int32

const (
	// EMPTY_OBSERVER_TYPE is the default value for the observer type
	ObservationType_EMPTY_OBSERVER_TYPE ObservationType = 0
	// IN_BOUND_TX is the observer type for inbound transactions
	ObservationType_IN_BOUND_TX ObservationType = 1
	// OUT_BOUND_TX is the observer type for outbound transactions
	ObservationType_OUT_BOUND_TX ObservationType = 2
	// TSS_KEY_GEN is the observer type for TSS key generation
	ObservationType_TSS_KEY_GEN ObservationType = 3
	// TSS_KEY_SIGN is the observer type for TSS key signing
	ObservationType_TSS_KEY_SIGN ObservationType = 4
	// IN_BOUND_BLOCK is the observer type for inbound blocks
	ObservationType_IN_BOUND_BLOCK ObservationType = 5
	// PELL_TOKEN_RECHARGE is the observer type for Pell token recharge
	ObservationType_PELL_TOKEN_RECHARGE ObservationType = 6
	// GAS_TOKEN_RECHARGE is the observer type for gas token recharge
	ObservationType_GAS_TOKEN_RECHARGE ObservationType = 7
)

var ObservationType_name = map[int32]string{
	0: "EMPTY_OBSERVER_TYPE",
	1: "IN_BOUND_TX",
	2: "OUT_BOUND_TX",
	3: "TSS_KEY_GEN",
	4: "TSS_KEY_SIGN",
	5: "IN_BOUND_BLOCK",
	6: "PELL_TOKEN_RECHARGE",
	7: "GAS_TOKEN_RECHARGE",
}

var ObservationType_value = map[string]int32{
	"EMPTY_OBSERVER_TYPE": 0,
	"IN_BOUND_TX":         1,
	"OUT_BOUND_TX":        2,
	"TSS_KEY_GEN":         3,
	"TSS_KEY_SIGN":        4,
	"IN_BOUND_BLOCK":      5,
	"PELL_TOKEN_RECHARGE": 6,
	"GAS_TOKEN_RECHARGE":  7,
}

func (x ObservationType) String() string {
	return proto.EnumName(ObservationType_name, int32(x))
}

func (ObservationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_66800904a3ba52be, []int{0}
}

// relayer update reason
type RelayerUpdateReason int32

const (
	// UNDEFINED is the default value for the relayer update reason
	RelayerUpdateReason_UNDEFINED RelayerUpdateReason = 0
	// TOMBSTONED is the relayer update reason for tombstoned relayers
	RelayerUpdateReason_TOMBSTONED RelayerUpdateReason = 1
	// ADMIN_UPDATE is the relayer update reason for admin updates
	RelayerUpdateReason_ADMIN_UPDATE RelayerUpdateReason = 2
)

var RelayerUpdateReason_name = map[int32]string{
	0: "UNDEFINED",
	1: "TOMBSTONED",
	2: "ADMIN_UPDATE",
}

var RelayerUpdateReason_value = map[string]int32{
	"UNDEFINED":    0,
	"TOMBSTONED":   1,
	"ADMIN_UPDATE": 2,
}

func (x RelayerUpdateReason) String() string {
	return proto.EnumName(RelayerUpdateReason_name, int32(x))
}

func (RelayerUpdateReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_66800904a3ba52be, []int{1}
}

// RelayerMapper is the mapper for relayers
type RelayerMapper struct {
	// index is the index of the relayer mapper
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// relayer_chain is the chain of the relayer mapper
	RelayerChain *chains.Chain `protobuf:"bytes,2,opt,name=relayer_chain,json=relayerChain,proto3" json:"relayer_chain,omitempty"`
	// relayer_list is the list of relayers
	RelayerList []string `protobuf:"bytes,3,rep,name=relayer_list,json=relayerList,proto3" json:"relayer_list,omitempty"`
}

func (m *RelayerMapper) Reset()         { *m = RelayerMapper{} }
func (m *RelayerMapper) String() string { return proto.CompactTextString(m) }
func (*RelayerMapper) ProtoMessage()    {}
func (*RelayerMapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_66800904a3ba52be, []int{0}
}
func (m *RelayerMapper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayerMapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayerMapper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayerMapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerMapper.Merge(m, src)
}
func (m *RelayerMapper) XXX_Size() int {
	return m.Size()
}
func (m *RelayerMapper) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerMapper.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerMapper proto.InternalMessageInfo

func (m *RelayerMapper) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *RelayerMapper) GetRelayerChain() *chains.Chain {
	if m != nil {
		return m.RelayerChain
	}
	return nil
}

func (m *RelayerMapper) GetRelayerList() []string {
	if m != nil {
		return m.RelayerList
	}
	return nil
}

// RelayerSet is the set of relayers
type RelayerSet struct {
	RelayerList []string `protobuf:"bytes,1,rep,name=relayer_list,json=relayerList,proto3" json:"relayer_list,omitempty"`
}

func (m *RelayerSet) Reset()         { *m = RelayerSet{} }
func (m *RelayerSet) String() string { return proto.CompactTextString(m) }
func (*RelayerSet) ProtoMessage()    {}
func (*RelayerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_66800904a3ba52be, []int{1}
}
func (m *RelayerSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayerSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerSet.Merge(m, src)
}
func (m *RelayerSet) XXX_Size() int {
	return m.Size()
}
func (m *RelayerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerSet.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerSet proto.InternalMessageInfo

func (m *RelayerSet) GetRelayerList() []string {
	if m != nil {
		return m.RelayerList
	}
	return nil
}

// LastRelayerCount is the last relayer count
type LastRelayerCount struct {
	// count is the count of the last relayer
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// last_change_height is the last change height of the relayer
	LastChangeHeight int64 `protobuf:"varint,2,opt,name=last_change_height,json=lastChangeHeight,proto3" json:"last_change_height,omitempty"`
}

func (m *LastRelayerCount) Reset()         { *m = LastRelayerCount{} }
func (m *LastRelayerCount) String() string { return proto.CompactTextString(m) }
func (*LastRelayerCount) ProtoMessage()    {}
func (*LastRelayerCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_66800904a3ba52be, []int{2}
}
func (m *LastRelayerCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LastRelayerCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LastRelayerCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LastRelayerCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastRelayerCount.Merge(m, src)
}
func (m *LastRelayerCount) XXX_Size() int {
	return m.Size()
}
func (m *LastRelayerCount) XXX_DiscardUnknown() {
	xxx_messageInfo_LastRelayerCount.DiscardUnknown(m)
}

var xxx_messageInfo_LastRelayerCount proto.InternalMessageInfo

func (m *LastRelayerCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LastRelayerCount) GetLastChangeHeight() int64 {
	if m != nil {
		return m.LastChangeHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("relayer.ObservationType", ObservationType_name, ObservationType_value)
	proto.RegisterEnum("relayer.RelayerUpdateReason", RelayerUpdateReason_name, RelayerUpdateReason_value)
	proto.RegisterType((*RelayerMapper)(nil), "relayer.RelayerMapper")
	proto.RegisterType((*RelayerSet)(nil), "relayer.RelayerSet")
	proto.RegisterType((*LastRelayerCount)(nil), "relayer.LastRelayerCount")
}

func init() { proto.RegisterFile("relayer/relayer.proto", fileDescriptor_66800904a3ba52be) }

var fileDescriptor_66800904a3ba52be = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcb, 0x6e, 0xda, 0x40,
	0x14, 0x65, 0x80, 0x24, 0x62, 0x08, 0xc9, 0x74, 0x92, 0x36, 0x88, 0x85, 0x45, 0xb3, 0x42, 0x51,
	0x85, 0xab, 0x56, 0xea, 0x9e, 0xc7, 0x14, 0x10, 0xc6, 0x46, 0x63, 0x13, 0x95, 0x6e, 0x46, 0x86,
	0x8c, 0x8c, 0x85, 0x6b, 0x5b, 0xf6, 0xa4, 0x85, 0x5d, 0x3f, 0xa1, 0x1f, 0xd1, 0x45, 0xff, 0xa1,
	0x3f, 0xd0, 0x65, 0x96, 0x5d, 0x56, 0xf0, 0x23, 0xd5, 0xd8, 0x43, 0x2b, 0x25, 0xab, 0x3b, 0xe7,
	0x9c, 0x7b, 0xee, 0x3d, 0x1a, 0x5d, 0xf8, 0x3c, 0xe1, 0x81, 0xbb, 0xe5, 0x89, 0xae, 0x6a, 0x3b,
	0x4e, 0x22, 0x11, 0xe1, 0x13, 0x05, 0x1b, 0x97, 0x5e, 0xe4, 0x45, 0x19, 0xa7, 0xcb, 0x57, 0x2e,
	0x37, 0xae, 0xe2, 0xb5, 0xa7, 0x2f, 0x57, 0xae, 0x1f, 0xa6, 0xaa, 0xe4, 0xc2, 0xf5, 0x57, 0x00,
	0x6b, 0x34, 0xb7, 0x4e, 0xdc, 0x38, 0xe6, 0x09, 0xbe, 0x84, 0x47, 0x7e, 0x78, 0xc7, 0x37, 0x75,
	0xd0, 0x04, 0xad, 0x0a, 0xcd, 0x01, 0x7e, 0x07, 0x6b, 0x6a, 0x03, 0xcb, 0xfc, 0xf5, 0x62, 0x13,
	0xb4, 0xaa, 0x6f, 0x9e, 0xb5, 0xe3, 0xb5, 0xd7, 0x56, 0x13, 0x7b, 0xb2, 0xd0, 0x53, 0xd5, 0x97,
	0x21, 0xfc, 0x12, 0x1e, 0x30, 0x0b, 0xfc, 0x54, 0xd4, 0x4b, 0xcd, 0x52, 0xab, 0x42, 0xab, 0x8a,
	0x33, 0xfc, 0x54, 0x5c, 0xeb, 0x10, 0xaa, 0x04, 0x36, 0x17, 0x4f, 0x0c, 0xe0, 0xa9, 0xe1, 0x16,
	0x22, 0xc3, 0x4d, 0x85, 0x32, 0xf5, 0xa2, 0xfb, 0x50, 0xc8, 0xd4, 0x4b, 0xf9, 0xc8, 0x52, 0x97,
	0x69, 0x0e, 0xf0, 0x2b, 0x88, 0x03, 0x37, 0x15, 0x32, 0x72, 0xe8, 0x71, 0xb6, 0xe2, 0xbe, 0xb7,
	0x12, 0x59, 0xf4, 0x12, 0x45, 0x52, 0xe9, 0x65, 0xc2, 0x30, 0xe3, 0x6f, 0x7e, 0x02, 0x78, 0x6e,
	0x2d, 0x52, 0x9e, 0x7c, 0x76, 0x85, 0x1f, 0x85, 0xce, 0x36, 0xe6, 0xf8, 0x0a, 0x5e, 0x90, 0xc9,
	0xd4, 0x99, 0x33, 0xab, 0x6b, 0x13, 0x7a, 0x4b, 0x28, 0x73, 0xe6, 0x53, 0x82, 0x0a, 0xf8, 0x1c,
	0x56, 0x47, 0x26, 0xeb, 0x5a, 0x33, 0xb3, 0xcf, 0x9c, 0x0f, 0x08, 0x60, 0x04, 0x4f, 0xad, 0x99,
	0xf3, 0x9f, 0x29, 0xca, 0x16, 0xc7, 0xb6, 0xd9, 0x98, 0xcc, 0xd9, 0x80, 0x98, 0xa8, 0x24, 0x5b,
	0x0e, 0x84, 0x3d, 0x1a, 0x98, 0xa8, 0x8c, 0x31, 0x3c, 0xfb, 0x37, 0xa5, 0x6b, 0x58, 0xbd, 0x31,
	0x3a, 0x92, 0x2b, 0xa7, 0xc4, 0x30, 0x98, 0x63, 0x8d, 0x89, 0xc9, 0x28, 0xe9, 0x0d, 0x3b, 0x74,
	0x40, 0xd0, 0x31, 0x7e, 0x01, 0xf1, 0xa0, 0x63, 0x3f, 0xe6, 0x4f, 0x1a, 0xe5, 0x1f, 0xdf, 0x35,
	0x70, 0x63, 0xc0, 0x0b, 0xf5, 0x23, 0xb3, 0xf8, 0xce, 0x15, 0x9c, 0x72, 0x37, 0x8d, 0x42, 0x5c,
	0x83, 0x95, 0x99, 0xd9, 0x27, 0xef, 0x47, 0x26, 0xe9, 0xa3, 0x02, 0x3e, 0x83, 0xd0, 0xb1, 0x26,
	0x5d, 0xdb, 0xb1, 0x24, 0xce, 0x52, 0x77, 0xfa, 0x93, 0x91, 0xc9, 0x66, 0xd3, 0x7e, 0xc7, 0x21,
	0xa8, 0x98, 0x4f, 0xeb, 0x0e, 0x7f, 0xed, 0x34, 0xf0, 0xb0, 0xd3, 0xc0, 0x9f, 0x9d, 0x06, 0xbe,
	0xed, 0xb5, 0xc2, 0xc3, 0x5e, 0x2b, 0xfc, 0xde, 0x6b, 0x85, 0x8f, 0x6d, 0xcf, 0x17, 0xab, 0xfb,
	0x45, 0x7b, 0x19, 0x7d, 0xd2, 0x5f, 0x6f, 0xa6, 0x3c, 0x08, 0x4c, 0x2e, 0xbe, 0x44, 0xc9, 0x5a,
	0x77, 0xb9, 0xe7, 0xa7, 0xfa, 0xe6, 0x70, 0x99, 0xba, 0xd8, 0xc6, 0x3c, 0x5d, 0x1c, 0x67, 0x87,
	0xf6, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x34, 0x12, 0x3d, 0xb9, 0x02, 0x00, 0x00,
}

func (m *RelayerMapper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayerMapper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayerMapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerList) > 0 {
		for iNdEx := len(m.RelayerList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RelayerList[iNdEx])
			copy(dAtA[i:], m.RelayerList[iNdEx])
			i = encodeVarintRelayer(dAtA, i, uint64(len(m.RelayerList[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.RelayerChain != nil {
		{
			size, err := m.RelayerChain.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelayer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintRelayer(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RelayerSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayerSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayerSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerList) > 0 {
		for iNdEx := len(m.RelayerList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RelayerList[iNdEx])
			copy(dAtA[i:], m.RelayerList[iNdEx])
			i = encodeVarintRelayer(dAtA, i, uint64(len(m.RelayerList[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *LastRelayerCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LastRelayerCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LastRelayerCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastChangeHeight != 0 {
		i = encodeVarintRelayer(dAtA, i, uint64(m.LastChangeHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Count != 0 {
		i = encodeVarintRelayer(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRelayer(dAtA []byte, offset int, v uint64) int {
	offset -= sovRelayer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RelayerMapper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovRelayer(uint64(l))
	}
	if m.RelayerChain != nil {
		l = m.RelayerChain.Size()
		n += 1 + l + sovRelayer(uint64(l))
	}
	if len(m.RelayerList) > 0 {
		for _, s := range m.RelayerList {
			l = len(s)
			n += 1 + l + sovRelayer(uint64(l))
		}
	}
	return n
}

func (m *RelayerSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RelayerList) > 0 {
		for _, s := range m.RelayerList {
			l = len(s)
			n += 1 + l + sovRelayer(uint64(l))
		}
	}
	return n
}

func (m *LastRelayerCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovRelayer(uint64(m.Count))
	}
	if m.LastChangeHeight != 0 {
		n += 1 + sovRelayer(uint64(m.LastChangeHeight))
	}
	return n
}

func sovRelayer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRelayer(x uint64) (n int) {
	return sovRelayer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RelayerMapper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelayer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayerMapper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayerMapper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerChain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelayer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RelayerChain == nil {
				m.RelayerChain = &chains.Chain{}
			}
			if err := m.RelayerChain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerList = append(m.RelayerList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelayer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelayer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayerSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelayer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayerSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayerSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerList = append(m.RelayerList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelayer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelayer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LastRelayerCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelayer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LastRelayerCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LastRelayerCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChangeHeight", wireType)
			}
			m.LastChangeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastChangeHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRelayer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelayer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRelayer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRelayer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRelayer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRelayer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRelayer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRelayer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRelayer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRelayer = fmt.Errorf("proto: unexpected end of group")
)
