// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emissions/events.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// emission type
type EmissionType int32

const (
	// slash
	EmissionType_SLASH EmissionType = 0
	// reward
	EmissionType_REWARDS EmissionType = 1
)

var EmissionType_name = map[int32]string{
	0: "SLASH",
	1: "REWARDS",
}

var EmissionType_value = map[string]int32{
	"SLASH":   0,
	"REWARDS": 1,
}

func (x EmissionType) String() string {
	return proto.EnumName(EmissionType_name, int32(x))
}

func (EmissionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff510015c00ef7ae, []int{0}
}

// relayer emission
type RelayerEmission struct {
	EmissionType    EmissionType          `protobuf:"varint,1,opt,name=emission_type,json=emissionType,proto3,enum=emissions.EmissionType" json:"emission_type,omitempty"`
	ObserverAddress string                `protobuf:"bytes,2,opt,name=observer_address,json=observerAddress,proto3" json:"observer_address,omitempty"`
	Amount          cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *RelayerEmission) Reset()         { *m = RelayerEmission{} }
func (m *RelayerEmission) String() string { return proto.CompactTextString(m) }
func (*RelayerEmission) ProtoMessage()    {}
func (*RelayerEmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff510015c00ef7ae, []int{0}
}
func (m *RelayerEmission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayerEmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayerEmission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayerEmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayerEmission.Merge(m, src)
}
func (m *RelayerEmission) XXX_Size() int {
	return m.Size()
}
func (m *RelayerEmission) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayerEmission.DiscardUnknown(m)
}

var xxx_messageInfo_RelayerEmission proto.InternalMessageInfo

func (m *RelayerEmission) GetEmissionType() EmissionType {
	if m != nil {
		return m.EmissionType
	}
	return EmissionType_SLASH
}

func (m *RelayerEmission) GetObserverAddress() string {
	if m != nil {
		return m.ObserverAddress
	}
	return ""
}

// relayer emissions event
type EventRelayerEmissions struct {
	MsgTypeUrl string             `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	Emissions  []*RelayerEmission `protobuf:"bytes,2,rep,name=emissions,proto3" json:"emissions,omitempty"`
}

func (m *EventRelayerEmissions) Reset()         { *m = EventRelayerEmissions{} }
func (m *EventRelayerEmissions) String() string { return proto.CompactTextString(m) }
func (*EventRelayerEmissions) ProtoMessage()    {}
func (*EventRelayerEmissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff510015c00ef7ae, []int{1}
}
func (m *EventRelayerEmissions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRelayerEmissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRelayerEmissions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRelayerEmissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRelayerEmissions.Merge(m, src)
}
func (m *EventRelayerEmissions) XXX_Size() int {
	return m.Size()
}
func (m *EventRelayerEmissions) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRelayerEmissions.DiscardUnknown(m)
}

var xxx_messageInfo_EventRelayerEmissions proto.InternalMessageInfo

func (m *EventRelayerEmissions) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *EventRelayerEmissions) GetEmissions() []*RelayerEmission {
	if m != nil {
		return m.Emissions
	}
	return nil
}

// block emissions event
type EventBlockEmissions struct {
	MsgTypeUrl               string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	BondFactor               string `protobuf:"bytes,2,opt,name=bond_factor,json=bondFactor,proto3" json:"bond_factor,omitempty"`
	ReservesFactor           string `protobuf:"bytes,3,opt,name=reserves_factor,json=reservesFactor,proto3" json:"reserves_factor,omitempty"`
	DurationFactor           string `protobuf:"bytes,4,opt,name=duration_factor,json=durationFactor,proto3" json:"duration_factor,omitempty"`
	ValidatorRewardsForBlock string `protobuf:"bytes,5,opt,name=validator_rewards_for_block,json=validatorRewardsForBlock,proto3" json:"validator_rewards_for_block,omitempty"`
	ObserverRewardsForBlock  string `protobuf:"bytes,6,opt,name=observer_rewards_for_block,json=observerRewardsForBlock,proto3" json:"observer_rewards_for_block,omitempty"`
	TssRewardsForBlock       string `protobuf:"bytes,7,opt,name=tss_rewards_for_block,json=tssRewardsForBlock,proto3" json:"tss_rewards_for_block,omitempty"`
}

func (m *EventBlockEmissions) Reset()         { *m = EventBlockEmissions{} }
func (m *EventBlockEmissions) String() string { return proto.CompactTextString(m) }
func (*EventBlockEmissions) ProtoMessage()    {}
func (*EventBlockEmissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff510015c00ef7ae, []int{2}
}
func (m *EventBlockEmissions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBlockEmissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBlockEmissions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBlockEmissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBlockEmissions.Merge(m, src)
}
func (m *EventBlockEmissions) XXX_Size() int {
	return m.Size()
}
func (m *EventBlockEmissions) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBlockEmissions.DiscardUnknown(m)
}

var xxx_messageInfo_EventBlockEmissions proto.InternalMessageInfo

func (m *EventBlockEmissions) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *EventBlockEmissions) GetBondFactor() string {
	if m != nil {
		return m.BondFactor
	}
	return ""
}

func (m *EventBlockEmissions) GetReservesFactor() string {
	if m != nil {
		return m.ReservesFactor
	}
	return ""
}

func (m *EventBlockEmissions) GetDurationFactor() string {
	if m != nil {
		return m.DurationFactor
	}
	return ""
}

func (m *EventBlockEmissions) GetValidatorRewardsForBlock() string {
	if m != nil {
		return m.ValidatorRewardsForBlock
	}
	return ""
}

func (m *EventBlockEmissions) GetObserverRewardsForBlock() string {
	if m != nil {
		return m.ObserverRewardsForBlock
	}
	return ""
}

func (m *EventBlockEmissions) GetTssRewardsForBlock() string {
	if m != nil {
		return m.TssRewardsForBlock
	}
	return ""
}

func init() {
	proto.RegisterEnum("emissions.EmissionType", EmissionType_name, EmissionType_value)
	proto.RegisterType((*RelayerEmission)(nil), "emissions.RelayerEmission")
	proto.RegisterType((*EventRelayerEmissions)(nil), "emissions.EventRelayerEmissions")
	proto.RegisterType((*EventBlockEmissions)(nil), "emissions.EventBlockEmissions")
}

func init() { proto.RegisterFile("emissions/events.proto", fileDescriptor_ff510015c00ef7ae) }

var fileDescriptor_ff510015c00ef7ae = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x29, 0xbb, 0xcb, 0x86, 0x07, 0x2e, 0x64, 0x14, 0xb7, 0xc1, 0x58, 0x08, 0x17, 0xd1,
	0x98, 0x76, 0x5d, 0x63, 0x62, 0xa2, 0x1e, 0x20, 0xb2, 0x51, 0x63, 0x8c, 0x19, 0x34, 0x26, 0x5e,
	0x9a, 0x81, 0xce, 0x76, 0x1b, 0xda, 0x0e, 0x99, 0x37, 0xb0, 0xcb, 0xb7, 0xf0, 0x43, 0x78, 0xf0,
	0xea, 0xb7, 0xd8, 0xe3, 0x1e, 0xd5, 0xc3, 0xc6, 0xc0, 0x17, 0x31, 0x1d, 0x5a, 0x20, 0xe8, 0xc5,
	0x5b, 0xfb, 0xcf, 0xef, 0x3f, 0xf3, 0x7f, 0xef, 0xcd, 0x83, 0xdb, 0x3c, 0x0a, 0x10, 0x03, 0x11,
	0xa3, 0xc3, 0xa7, 0x3c, 0x56, 0x68, 0x8f, 0xa5, 0x50, 0x82, 0x14, 0x57, 0x7a, 0xfd, 0x96, 0x2f,
	0x7c, 0xa1, 0x55, 0x27, 0xf9, 0x5a, 0x02, 0xad, 0xef, 0x06, 0x54, 0x28, 0x0f, 0xd9, 0x8c, 0xcb,
	0x5e, 0x8a, 0x92, 0xe7, 0x70, 0x23, 0xb3, 0xb9, 0x6a, 0x36, 0xe6, 0xa6, 0xd1, 0x34, 0xda, 0x07,
	0xc7, 0x87, 0xf6, 0xea, 0x30, 0x3b, 0x63, 0x3f, 0xcc, 0xc6, 0x9c, 0x96, 0xf9, 0xc6, 0x1f, 0xb9,
	0x0f, 0x55, 0x31, 0x40, 0x2e, 0xa7, 0x5c, 0xba, 0xcc, 0xf3, 0x24, 0x47, 0x34, 0xf3, 0x4d, 0xa3,
	0x5d, 0xa4, 0x95, 0x4c, 0xef, 0x2c, 0x65, 0xf2, 0x04, 0x0a, 0x2c, 0x12, 0x93, 0x58, 0x99, 0x3b,
	0x09, 0xd0, 0xbd, 0x7b, 0x79, 0xdd, 0xc8, 0xfd, 0xba, 0x6e, 0xd4, 0x86, 0x02, 0x23, 0x81, 0xe8,
	0x8d, 0xec, 0x40, 0x38, 0x11, 0x53, 0x67, 0xf6, 0xeb, 0x58, 0xd1, 0x14, 0x6e, 0x21, 0xd4, 0x7a,
	0x49, 0x91, 0x5b, 0xb9, 0x91, 0x34, 0xa1, 0x1c, 0xa1, 0xaf, 0x33, 0xbb, 0x13, 0x19, 0xea, 0xdc,
	0x45, 0x0a, 0x11, 0xfa, 0x49, 0xb2, 0x8f, 0x32, 0x24, 0x4f, 0x61, 0xdd, 0x11, 0x33, 0xdf, 0xdc,
	0x69, 0x97, 0x8e, 0xeb, 0x1b, 0x65, 0x6d, 0x9d, 0x48, 0xd7, 0x70, 0xeb, 0x67, 0x1e, 0x6e, 0xea,
	0x5b, 0xbb, 0xa1, 0x18, 0x8e, 0xfe, 0xe7, 0xce, 0x06, 0x94, 0x06, 0x22, 0xf6, 0xdc, 0x53, 0x36,
	0x54, 0x42, 0xa6, 0xbd, 0x80, 0x44, 0x3a, 0xd1, 0x0a, 0xb9, 0x07, 0x15, 0xc9, 0x75, 0x67, 0x30,
	0x83, 0x74, 0x3f, 0xe8, 0x41, 0x26, 0xaf, 0x41, 0x6f, 0x22, 0x99, 0x4a, 0x06, 0x93, 0x82, 0xbb,
	0x4b, 0x30, 0x93, 0x53, 0xf0, 0x05, 0xdc, 0x99, 0xb2, 0x30, 0xf0, 0x98, 0x12, 0xd2, 0x95, 0xfc,
	0x9c, 0x49, 0x0f, 0xdd, 0x53, 0x21, 0xdd, 0x41, 0x12, 0xde, 0xdc, 0xd3, 0x26, 0x73, 0x85, 0xd0,
	0x25, 0x71, 0x22, 0xa4, 0x2e, 0x8e, 0x3c, 0x83, 0xfa, 0x6a, 0x84, 0x7f, 0xbb, 0x0b, 0xda, 0x7d,
	0x98, 0x11, 0xdb, 0xe6, 0x47, 0x50, 0x53, 0x88, 0xff, 0xf0, 0xed, 0x6b, 0x1f, 0x51, 0x88, 0x5b,
	0x96, 0x07, 0x0f, 0xa1, 0xbc, 0xf9, 0xa0, 0x48, 0x11, 0xf6, 0xfa, 0x6f, 0x3b, 0xfd, 0x57, 0xd5,
	0x1c, 0x29, 0xc1, 0x3e, 0xed, 0x7d, 0xea, 0xd0, 0x97, 0xfd, 0xaa, 0x51, 0xdf, 0xfd, 0xf6, 0xd5,
	0x32, 0xba, 0x6f, 0x2e, 0xe7, 0x96, 0x71, 0x35, 0xb7, 0x8c, 0xdf, 0x73, 0xcb, 0xf8, 0xb2, 0xb0,
	0x72, 0x57, 0x0b, 0x2b, 0xf7, 0x63, 0x61, 0xe5, 0x3e, 0x1f, 0xf9, 0x81, 0x3a, 0x9b, 0x0c, 0xec,
	0xa1, 0x88, 0x9c, 0xa3, 0x8b, 0xf7, 0x3c, 0x0c, 0xdf, 0x71, 0x75, 0x2e, 0xe4, 0xc8, 0x61, 0xdc,
	0x0f, 0xd0, 0xb9, 0x70, 0xd6, 0x6b, 0x92, 0x0c, 0x0c, 0x07, 0x05, 0xbd, 0x05, 0x8f, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x86, 0x4b, 0xd6, 0x9c, 0x40, 0x03, 0x00, 0x00,
}

func (m *RelayerEmission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayerEmission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayerEmission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ObserverAddress) > 0 {
		i -= len(m.ObserverAddress)
		copy(dAtA[i:], m.ObserverAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ObserverAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.EmissionType != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.EmissionType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventRelayerEmissions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRelayerEmissions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRelayerEmissions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Emissions) > 0 {
		for iNdEx := len(m.Emissions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Emissions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBlockEmissions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBlockEmissions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBlockEmissions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TssRewardsForBlock) > 0 {
		i -= len(m.TssRewardsForBlock)
		copy(dAtA[i:], m.TssRewardsForBlock)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TssRewardsForBlock)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ObserverRewardsForBlock) > 0 {
		i -= len(m.ObserverRewardsForBlock)
		copy(dAtA[i:], m.ObserverRewardsForBlock)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ObserverRewardsForBlock)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ValidatorRewardsForBlock) > 0 {
		i -= len(m.ValidatorRewardsForBlock)
		copy(dAtA[i:], m.ValidatorRewardsForBlock)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ValidatorRewardsForBlock)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DurationFactor) > 0 {
		i -= len(m.DurationFactor)
		copy(dAtA[i:], m.DurationFactor)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.DurationFactor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReservesFactor) > 0 {
		i -= len(m.ReservesFactor)
		copy(dAtA[i:], m.ReservesFactor)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReservesFactor)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BondFactor) > 0 {
		i -= len(m.BondFactor)
		copy(dAtA[i:], m.BondFactor)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.BondFactor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RelayerEmission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EmissionType != 0 {
		n += 1 + sovEvents(uint64(m.EmissionType))
	}
	l = len(m.ObserverAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventRelayerEmissions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if len(m.Emissions) > 0 {
		for _, e := range m.Emissions {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	return n
}

func (m *EventBlockEmissions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.BondFactor)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ReservesFactor)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.DurationFactor)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ValidatorRewardsForBlock)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ObserverRewardsForBlock)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.TssRewardsForBlock)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RelayerEmission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayerEmission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayerEmission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionType", wireType)
			}
			m.EmissionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmissionType |= EmissionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObserverAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObserverAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRelayerEmissions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRelayerEmissions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRelayerEmissions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Emissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Emissions = append(m.Emissions, &RelayerEmission{})
			if err := m.Emissions[len(m.Emissions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBlockEmissions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBlockEmissions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBlockEmissions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservesFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservesFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DurationFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRewardsForBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorRewardsForBlock = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObserverRewardsForBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObserverRewardsForBlock = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TssRewardsForBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TssRewardsForBlock = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
