version: "3"

# This docker-compose file overrides the orchestrator service to specify the flag to test performance of xmsgs
# and skip the regular tests

services:
  orchestrator:
    entrypoint: ["/work/start-pelle2e.sh", "local --test-performance"]

