# This docker-compose file configures the localnet environment
# it contains the following services:
# - pellChain with 2 nodes (pellcore0, pellcore1)
# - A observer set with 2 clients (pellclient0, pellclient1)
# - An Ethereum node (eth)
# - A Bitcoin node (bitcoin)
# - A Rosetta API (rosetta)
# - An orchestrator to manage interaction with the localnet (orchestrator)

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  # rosetta:
  #   image: pellnode:latest
  #   container_name: rosetta
  #   hostname: rosetta
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.20.0.200
  #   entrypoint: ["pellcored", "rosetta", "--tendermint", "pellcore0:26657", "--grpc", "pellcore0:9090", "--network", "ignite_186-1", "--blockchain",  "pellcore"]

  pellcore0:
    image: pellnode:latest
    container_name: pellcore0
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: pellcore0
    ports:
      - "1317:1317"
      - "9545:8545"
      - "9546:8546"
      - "26657:26657"
      - "26660:26660"
      - "6060:6060"
      - "9090:9090"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11
    entrypoint: ["/root/start-pellcored.sh", "2"]
    volumes:
      - ./scripts/start-pellcored.sh:/root/start-pellcored.sh
    environment:
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only

  pellcore1:
    image: pellnode:latest
    container_name: pellcore1
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: pellcore1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12
    entrypoint: ["/root/start-pellcored.sh", "2"]
    volumes:
      - ./scripts/start-pellcored.sh:/root/start-pellcored.sh
    environment:
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only


  pellclient0:
    image: pellnode:latest
    container_name: pellclient0
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: pellclient0
    networks:
      mynetwork:
        ipv4_address: 172.20.0.21
    entrypoint: /root/start-pellclientd.sh
    volumes:
      - ./scripts/start-pellclientd.sh:/root/start-pellclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
      - BSC_EXTERNAL_RPC_URL=$BSC_EXTERNAL_RPC_URL
      - MANTLE_TESTNET_EXTERNAL_RPC_URL=$MANTLE_TESTNET_EXTERNAL_RPC_URL
      - CORE_TESTNET_EXTERNAL_RPC_URL=$CORE_TESTNET_EXTERNAL_RPC_URL
  pellclient1:
    image: pellnode:latest
    container_name: pellclient1
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: pellclient1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.22
    entrypoint: /root/start-pellclientd.sh
    volumes:
      - ./scripts/start-pellclientd.sh:/root/start-pellclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=file
      - HOTKEY_PASSWORD=password # test purposes only
      - BSC_EXTERNAL_RPC_URL=$BSC_EXTERNAL_RPC_URL
      - MANTLE_TESTNET_EXTERNAL_RPC_URL=$MANTLE_TESTNET_EXTERNAL_RPC_URL
      - CORE_TESTNET_EXTERNAL_RPC_URL=$CORE_TESTNET_EXTERNAL_RPC_URL

  # bitcoin:
  #   image: ruimarinho/bitcoin-core:22 # version 23 is not working with btcd 0.22.0 due to change in createwallet rpc
  #   container_name: bitcoin
  #   hostname: bitcoin
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.20.0.101
  #   ports:
  #     - "18443:18443"
  #   command:
  #     -printtoconsole
  #     -regtest=1
  #     -rpcallowip=0.0.0.0/0
  #     -rpcbind=0.0.0.0
  #     -rpcauth=smoketest:63acf9b8dccecce914d85ff8c044b78b$$5892f9bbc84f4364e79f0970039f88bdd823f168d4acc76099ab97b14a766a99
  #     -txindex=1

  hardhat:
    image: pell-contracts:${TAG:-latest}
    container_name: hardhat
    hostname: hardhat
    environment:
      - LOCALHOST_URL=http://eth:8545
      - PELL_URL=http://pellcore0:8545
    depends_on:
      - eth

  eth:
    image: geth:${TAG:-latest}
    container_name: eth
    hostname: eth
    ports:
      - "8545:8545"

  orchestrator:
    image: orchestrator:latest
    tty: true
    container_name: orchestrator
    build:
      context: ../../.
      dockerfile: contrib/localnet/orchestrator/Dockerfile
    depends_on:
      - pellcore0
      - eth
    hostname: orchestrator
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    entrypoint: ["/work/start-e2e-testnet.sh"]

