// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file xmsg/events.proto (package pellchain.pellcore.xmsg, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * inbound tx finalized event
 *
 * @generated from message pellchain.pellcore.xmsg.EventInboundFinalized
 */
export declare class EventInboundFinalized extends Message<EventInboundFinalized> {
  /**
   * @generated from field: string msg_type_url = 1;
   */
  msgTypeUrl: string;

  /**
   * @generated from field: string xmsg_index = 2;
   */
  xmsgIndex: string;

  /**
   * @generated from field: string sender = 3;
   */
  sender: string;

  /**
   * @generated from field: string tx_orgin = 4;
   */
  txOrgin: string;

  /**
   * @generated from field: string in_tx_hash = 6;
   */
  inTxHash: string;

  /**
   * @generated from field: string in_block_height = 7;
   */
  inBlockHeight: string;

  /**
   * @generated from field: string receiver = 8;
   */
  receiver: string;

  /**
   * @generated from field: string receiver_chain = 9;
   */
  receiverChain: string;

  /**
   * @generated from field: string new_status = 12;
   */
  newStatus: string;

  /**
   * @generated from field: string status_message = 13;
   */
  statusMessage: string;

  /**
   * @generated from field: string sender_chain = 14;
   */
  senderChain: string;

  constructor(data?: PartialMessage<EventInboundFinalized>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.EventInboundFinalized";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventInboundFinalized;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventInboundFinalized;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventInboundFinalized;

  static equals(a: EventInboundFinalized | PlainMessage<EventInboundFinalized> | undefined, b: EventInboundFinalized | PlainMessage<EventInboundFinalized> | undefined): boolean;
}

/**
 * outbound tx failure event
 *
 * @generated from message pellchain.pellcore.xmsg.EventOutboundFailure
 */
export declare class EventOutboundFailure extends Message<EventOutboundFailure> {
  /**
   * @generated from field: string msg_type_url = 1;
   */
  msgTypeUrl: string;

  /**
   * @generated from field: string xmsg_index = 2;
   */
  xmsgIndex: string;

  /**
   * @generated from field: string old_status = 3;
   */
  oldStatus: string;

  /**
   * @generated from field: string new_status = 4;
   */
  newStatus: string;

  constructor(data?: PartialMessage<EventOutboundFailure>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.EventOutboundFailure";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventOutboundFailure;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventOutboundFailure;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventOutboundFailure;

  static equals(a: EventOutboundFailure | PlainMessage<EventOutboundFailure> | undefined, b: EventOutboundFailure | PlainMessage<EventOutboundFailure> | undefined): boolean;
}

/**
 * outbound tx successful event
 *
 * @generated from message pellchain.pellcore.xmsg.EventOutboundSuccess
 */
export declare class EventOutboundSuccess extends Message<EventOutboundSuccess> {
  /**
   * @generated from field: string msg_type_url = 1;
   */
  msgTypeUrl: string;

  /**
   * @generated from field: string xmsg_index = 2;
   */
  xmsgIndex: string;

  /**
   * @generated from field: string old_status = 3;
   */
  oldStatus: string;

  /**
   * @generated from field: string new_status = 4;
   */
  newStatus: string;

  constructor(data?: PartialMessage<EventOutboundSuccess>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.EventOutboundSuccess";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventOutboundSuccess;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventOutboundSuccess;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventOutboundSuccess;

  static equals(a: EventOutboundSuccess | PlainMessage<EventOutboundSuccess> | undefined, b: EventOutboundSuccess | PlainMessage<EventOutboundSuccess> | undefined): boolean;
}

/**
 * pell sent msg event
 *
 * @generated from message pellchain.pellcore.xmsg.EventPellSent
 */
export declare class EventPellSent extends Message<EventPellSent> {
  /**
   * @generated from field: string msg_type_url = 1;
   */
  msgTypeUrl: string;

  /**
   * @generated from field: string xmsg_index = 2;
   */
  xmsgIndex: string;

  /**
   * @generated from field: string sender = 3;
   */
  sender: string;

  /**
   * @generated from field: string sender_chain = 4;
   */
  senderChain: string;

  /**
   * @generated from field: string in_tx_hash = 5;
   */
  inTxHash: string;

  /**
   * @generated from field: string receiver = 6;
   */
  receiver: string;

  /**
   * @generated from field: string receiver_chain = 7;
   */
  receiverChain: string;

  /**
   * @generated from field: string pell_tx_origin = 8;
   */
  pellTxOrigin: string;

  /**
   * @generated from field: string pell_sender = 9;
   */
  pellSender: string;

  /**
   * @generated from field: string pell_receiver = 10;
   */
  pellReceiver: string;

  /**
   * @generated from field: int64 pell_receiver_chain_id = 11;
   */
  pellReceiverChainId: bigint;

  /**
   * @generated from field: string pell_message = 12;
   */
  pellMessage: string;

  /**
   * @generated from field: string pell_params = 13;
   */
  pellParams: string;

  /**
   * @generated from field: string new_status = 14;
   */
  newStatus: string;

  constructor(data?: PartialMessage<EventPellSent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.EventPellSent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPellSent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPellSent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPellSent;

  static equals(a: EventPellSent | PlainMessage<EventPellSent> | undefined, b: EventPellSent | PlainMessage<EventPellSent> | undefined): boolean;
}

/**
 * increased xmsg gas price event
 *
 * @generated from message pellchain.pellcore.xmsg.EventXmsgGasPriceIncreased
 */
export declare class EventXmsgGasPriceIncreased extends Message<EventXmsgGasPriceIncreased> {
  /**
   * @generated from field: string xmsg_index = 1;
   */
  xmsgIndex: string;

  /**
   * @generated from field: string gas_price_increase = 2;
   */
  gasPriceIncrease: string;

  /**
   * @generated from field: string additional_fees = 3;
   */
  additionalFees: string;

  constructor(data?: PartialMessage<EventXmsgGasPriceIncreased>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.EventXmsgGasPriceIncreased";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventXmsgGasPriceIncreased;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventXmsgGasPriceIncreased;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventXmsgGasPriceIncreased;

  static equals(a: EventXmsgGasPriceIncreased | PlainMessage<EventXmsgGasPriceIncreased> | undefined, b: EventXmsgGasPriceIncreased | PlainMessage<EventXmsgGasPriceIncreased> | undefined): boolean;
}

