// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file xmsg/out_tx_tracker.proto (package pellchain.pellcore.xmsg, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * transaction hash list
 *
 * @generated from message pellchain.pellcore.xmsg.TxHashList
 */
export declare class TxHashList extends Message<TxHashList> {
  /**
   * @generated from field: string tx_hash = 1;
   */
  txHash: string;

  /**
   * @generated from field: string tx_signer = 2;
   */
  txSigner: string;

  /**
   * @generated from field: bool proved = 3;
   */
  proved: boolean;

  constructor(data?: PartialMessage<TxHashList>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.TxHashList";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TxHashList;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TxHashList;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TxHashList;

  static equals(a: TxHashList | PlainMessage<TxHashList> | undefined, b: TxHashList | PlainMessage<TxHashList> | undefined): boolean;
}

/**
 * outbound transaction tracker
 *
 * @generated from message pellchain.pellcore.xmsg.OutTxTracker
 */
export declare class OutTxTracker extends Message<OutTxTracker> {
  /**
   * format: "chain-nonce"
   *
   * @generated from field: string index = 1;
   */
  index: string;

  /**
   * @generated from field: int64 chain_id = 2;
   */
  chainId: bigint;

  /**
   * @generated from field: uint64 nonce = 3;
   */
  nonce: bigint;

  /**
   * @generated from field: repeated pellchain.pellcore.xmsg.TxHashList hash_lists = 4;
   */
  hashLists: TxHashList[];

  constructor(data?: PartialMessage<OutTxTracker>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.OutTxTracker";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OutTxTracker;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OutTxTracker;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OutTxTracker;

  static equals(a: OutTxTracker | PlainMessage<OutTxTracker> | undefined, b: OutTxTracker | PlainMessage<OutTxTracker> | undefined): boolean;
}

