// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file xmsg/rate_limiter_flags.proto (package pellchain.pellcore.xmsg, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * rate limiter setting
 *
 * @generated from message pellchain.pellcore.xmsg.RateLimiterFlags
 */
export declare class RateLimiterFlags extends Message<RateLimiterFlags> {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * window in blocks
   *
   * @generated from field: int64 window = 2;
   */
  window: bigint;

  /**
   * rate in apell per block
   *
   * @generated from field: string rate = 3;
   */
  rate: string;

  constructor(data?: PartialMessage<RateLimiterFlags>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.xmsg.RateLimiterFlags";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RateLimiterFlags;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RateLimiterFlags;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RateLimiterFlags;

  static equals(a: RateLimiterFlags | PlainMessage<RateLimiterFlags> | undefined, b: RateLimiterFlags | PlainMessage<RateLimiterFlags> | undefined): boolean;
}

