// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file pevm/events.proto (package pellchain.pellcore.pevm, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * deploy pell system contract event
 *
 * @generated from message pellchain.pellcore.pevm.EventSystemContractsDeployed
 */
export declare class EventSystemContractsDeployed extends Message<EventSystemContractsDeployed> {
  /**
   * @generated from field: string msg_type_url = 1;
   */
  msgTypeUrl: string;

  /**
   * @generated from field: string system_contract = 2;
   */
  systemContract: string;

  /**
   * @generated from field: string connector = 3;
   */
  connector: string;

  /**
   * @generated from field: string empty_contract = 4;
   */
  emptyContract: string;

  /**
   * @generated from field: string proxy_admin = 5;
   */
  proxyAdmin: string;

  /**
   * @generated from field: string delegation_manager_proxy = 6;
   */
  delegationManagerProxy: string;

  /**
   * @generated from field: string delegation_manager_interactor_proxy = 7;
   */
  delegationManagerInteractorProxy: string;

  /**
   * @generated from field: string strategy_manager_proxy = 8;
   */
  strategyManagerProxy: string;

  /**
   * @generated from field: string slasher_proxy = 9;
   */
  slasherProxy: string;

  /**
   * @generated from field: string delegation_manager_impl = 10;
   */
  delegationManagerImpl: string;

  /**
   * @generated from field: string delegation_manager_interactor_impl = 11;
   */
  delegationManagerInteractorImpl: string;

  /**
   * @generated from field: string strategy_manager_impl = 12;
   */
  strategyManagerImpl: string;

  /**
   * @generated from field: string slasher_impl = 13;
   */
  slasherImpl: string;

  /**
   * @generated from field: string dvs_directory = 14;
   */
  dvsDirectory: string;

  /**
   * @generated from field: string dvs_directory_proxy = 15;
   */
  dvsDirectoryProxy: string;

  /**
   * @generated from field: string registry_router = 16;
   */
  registryRouter: string;

  /**
   * @generated from field: string registry_router_factory = 17;
   */
  registryRouterFactory: string;

  /**
   * @generated from field: string signer = 18;
   */
  signer: string;

  constructor(data?: PartialMessage<EventSystemContractsDeployed>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.pevm.EventSystemContractsDeployed";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventSystemContractsDeployed;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventSystemContractsDeployed;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventSystemContractsDeployed;

  static equals(a: EventSystemContractsDeployed | PlainMessage<EventSystemContractsDeployed> | undefined, b: EventSystemContractsDeployed | PlainMessage<EventSystemContractsDeployed> | undefined): boolean;
}

