// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file pevm/query.proto (package pellchain.pellcore.pevm, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { SystemContract } from "./system_contract_pb.js";

/**
 * request of query system contract
 *
 * @generated from message pellchain.pellcore.pevm.QueryGetSystemContractRequest
 */
export declare class QueryGetSystemContractRequest extends Message<QueryGetSystemContractRequest> {
  constructor(data?: PartialMessage<QueryGetSystemContractRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.pevm.QueryGetSystemContractRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetSystemContractRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetSystemContractRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetSystemContractRequest;

  static equals(a: QueryGetSystemContractRequest | PlainMessage<QueryGetSystemContractRequest> | undefined, b: QueryGetSystemContractRequest | PlainMessage<QueryGetSystemContractRequest> | undefined): boolean;
}

/**
 * response of query system contract
 *
 * @generated from message pellchain.pellcore.pevm.SystemContractResponse
 */
export declare class SystemContractResponse extends Message<SystemContractResponse> {
  /**
   * @generated from field: pellchain.pellcore.pevm.SystemContract system_contract = 1;
   */
  systemContract?: SystemContract;

  constructor(data?: PartialMessage<SystemContractResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.pevm.SystemContractResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SystemContractResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SystemContractResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SystemContractResponse;

  static equals(a: SystemContractResponse | PlainMessage<SystemContractResponse> | undefined, b: SystemContractResponse | PlainMessage<SystemContractResponse> | undefined): boolean;
}

