// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file lightclient/query.proto (package pellchain.pellcore.lightclient, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { PageRequest, PageResponse } from "../cosmos/base/query/v1beta1/pagination_pb.js";
import type { BlockHeader, Proof } from "../pkg/proofs/proofs_pb.js";
import type { ChainState } from "./chain_state_pb.js";
import type { VerificationFlags } from "./verification_flags_pb.js";

/**
 * query all block header request
 *
 * @generated from message pellchain.pellcore.lightclient.QueryAllBlockHeaderRequest
 */
export declare class QueryAllBlockHeaderRequest extends Message<QueryAllBlockHeaderRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllBlockHeaderRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryAllBlockHeaderRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllBlockHeaderRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllBlockHeaderRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllBlockHeaderRequest;

  static equals(a: QueryAllBlockHeaderRequest | PlainMessage<QueryAllBlockHeaderRequest> | undefined, b: QueryAllBlockHeaderRequest | PlainMessage<QueryAllBlockHeaderRequest> | undefined): boolean;
}

/**
 * response of query all block header
 *
 * @generated from message pellchain.pellcore.lightclient.QueryBlockHeaderAllResponse
 */
export declare class QueryBlockHeaderAllResponse extends Message<QueryBlockHeaderAllResponse> {
  /**
   * @generated from field: repeated proofs.BlockHeader block_headers = 1;
   */
  blockHeaders: BlockHeader[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryBlockHeaderAllResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryBlockHeaderAllResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlockHeaderAllResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlockHeaderAllResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlockHeaderAllResponse;

  static equals(a: QueryBlockHeaderAllResponse | PlainMessage<QueryBlockHeaderAllResponse> | undefined, b: QueryBlockHeaderAllResponse | PlainMessage<QueryBlockHeaderAllResponse> | undefined): boolean;
}

/**
 * query block header request
 *
 * @generated from message pellchain.pellcore.lightclient.QueryGetBlockHeaderRequest
 */
export declare class QueryGetBlockHeaderRequest extends Message<QueryGetBlockHeaderRequest> {
  /**
   * @generated from field: bytes block_hash = 1;
   */
  blockHash: Uint8Array;

  constructor(data?: PartialMessage<QueryGetBlockHeaderRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryGetBlockHeaderRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetBlockHeaderRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetBlockHeaderRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetBlockHeaderRequest;

  static equals(a: QueryGetBlockHeaderRequest | PlainMessage<QueryGetBlockHeaderRequest> | undefined, b: QueryGetBlockHeaderRequest | PlainMessage<QueryGetBlockHeaderRequest> | undefined): boolean;
}

/**
 * response of query block header
 *
 * @generated from message pellchain.pellcore.lightclient.QueryBlockHeaderResponse
 */
export declare class QueryBlockHeaderResponse extends Message<QueryBlockHeaderResponse> {
  /**
   * @generated from field: proofs.BlockHeader block_header = 1;
   */
  blockHeader?: BlockHeader;

  constructor(data?: PartialMessage<QueryBlockHeaderResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryBlockHeaderResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlockHeaderResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlockHeaderResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlockHeaderResponse;

  static equals(a: QueryBlockHeaderResponse | PlainMessage<QueryBlockHeaderResponse> | undefined, b: QueryBlockHeaderResponse | PlainMessage<QueryBlockHeaderResponse> | undefined): boolean;
}

/**
 * query all chain state request
 *
 * @generated from message pellchain.pellcore.lightclient.QueryAllChainStateRequest
 */
export declare class QueryAllChainStateRequest extends Message<QueryAllChainStateRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllChainStateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryAllChainStateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllChainStateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllChainStateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllChainStateRequest;

  static equals(a: QueryAllChainStateRequest | PlainMessage<QueryAllChainStateRequest> | undefined, b: QueryAllChainStateRequest | PlainMessage<QueryAllChainStateRequest> | undefined): boolean;
}

/**
 * response of query all chain state
 *
 * @generated from message pellchain.pellcore.lightclient.QueryChainStateAllResponse
 */
export declare class QueryChainStateAllResponse extends Message<QueryChainStateAllResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.lightclient.ChainState chain_state = 1;
   */
  chainState: ChainState[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryChainStateAllResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryChainStateAllResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryChainStateAllResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryChainStateAllResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryChainStateAllResponse;

  static equals(a: QueryChainStateAllResponse | PlainMessage<QueryChainStateAllResponse> | undefined, b: QueryChainStateAllResponse | PlainMessage<QueryChainStateAllResponse> | undefined): boolean;
}

/**
 * request of query chain state
 *
 * @generated from message pellchain.pellcore.lightclient.QueryGetChainStateRequest
 */
export declare class QueryGetChainStateRequest extends Message<QueryGetChainStateRequest> {
  /**
   * @generated from field: int64 chain_id = 1;
   */
  chainId: bigint;

  constructor(data?: PartialMessage<QueryGetChainStateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryGetChainStateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainStateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainStateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainStateRequest;

  static equals(a: QueryGetChainStateRequest | PlainMessage<QueryGetChainStateRequest> | undefined, b: QueryGetChainStateRequest | PlainMessage<QueryGetChainStateRequest> | undefined): boolean;
}

/**
 * response of query chain state
 *
 * @generated from message pellchain.pellcore.lightclient.QueryChainStateResponse
 */
export declare class QueryChainStateResponse extends Message<QueryChainStateResponse> {
  /**
   * @generated from field: pellchain.pellcore.lightclient.ChainState chain_state = 1;
   */
  chainState?: ChainState;

  constructor(data?: PartialMessage<QueryChainStateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryChainStateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryChainStateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryChainStateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryChainStateResponse;

  static equals(a: QueryChainStateResponse | PlainMessage<QueryChainStateResponse> | undefined, b: QueryChainStateResponse | PlainMessage<QueryChainStateResponse> | undefined): boolean;
}

/**
 * request of query is valid prove
 *
 * @generated from message pellchain.pellcore.lightclient.QueryProveRequest
 */
export declare class QueryProveRequest extends Message<QueryProveRequest> {
  /**
   * @generated from field: int64 chain_id = 1;
   */
  chainId: bigint;

  /**
   * @generated from field: string tx_hash = 2;
   */
  txHash: string;

  /**
   * @generated from field: proofs.Proof proof = 3;
   */
  proof?: Proof;

  /**
   * @generated from field: string block_hash = 4;
   */
  blockHash: string;

  /**
   * @generated from field: int64 tx_index = 5;
   */
  txIndex: bigint;

  constructor(data?: PartialMessage<QueryProveRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryProveRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryProveRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryProveRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryProveRequest;

  static equals(a: QueryProveRequest | PlainMessage<QueryProveRequest> | undefined, b: QueryProveRequest | PlainMessage<QueryProveRequest> | undefined): boolean;
}

/**
 * response of is valid prove
 *
 * @generated from message pellchain.pellcore.lightclient.QueryProveResponse
 */
export declare class QueryProveResponse extends Message<QueryProveResponse> {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  constructor(data?: PartialMessage<QueryProveResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryProveResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryProveResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryProveResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryProveResponse;

  static equals(a: QueryProveResponse | PlainMessage<QueryProveResponse> | undefined, b: QueryProveResponse | PlainMessage<QueryProveResponse> | undefined): boolean;
}

/**
 * request of query verification flags
 *
 * @generated from message pellchain.pellcore.lightclient.QueryVerificationFlagsRequest
 */
export declare class QueryVerificationFlagsRequest extends Message<QueryVerificationFlagsRequest> {
  constructor(data?: PartialMessage<QueryVerificationFlagsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryVerificationFlagsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryVerificationFlagsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryVerificationFlagsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryVerificationFlagsRequest;

  static equals(a: QueryVerificationFlagsRequest | PlainMessage<QueryVerificationFlagsRequest> | undefined, b: QueryVerificationFlagsRequest | PlainMessage<QueryVerificationFlagsRequest> | undefined): boolean;
}

/**
 * response of query verification flags
 *
 * @generated from message pellchain.pellcore.lightclient.QueryVerificationFlagsResponse
 */
export declare class QueryVerificationFlagsResponse extends Message<QueryVerificationFlagsResponse> {
  /**
   * @generated from field: pellchain.pellcore.lightclient.VerificationFlags verification_flags = 1;
   */
  verificationFlags?: VerificationFlags;

  constructor(data?: PartialMessage<QueryVerificationFlagsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.lightclient.QueryVerificationFlagsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryVerificationFlagsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryVerificationFlagsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryVerificationFlagsResponse;

  static equals(a: QueryVerificationFlagsResponse | PlainMessage<QueryVerificationFlagsResponse> | undefined, b: QueryVerificationFlagsResponse | PlainMessage<QueryVerificationFlagsResponse> | undefined): boolean;
}

