// @generated by protoc-gen-es v1.3.0 with parameter "target=dts"
// @generated from file relayer/query.proto (package pellchain.pellcore.relayer, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ChainNonces } from "./chain_nonces_pb.js";
import type { PageRequest, PageResponse } from "../cosmos/base/query/v1beta1/pagination_pb.js";
import type { PendingNonces } from "./pending_nonces_pb.js";
import type { TSS } from "./tss_pb.js";
import type { ChainParams, ChainParamsList, Params } from "./params_pb.js";
import type { BallotStatus, VoteType } from "./ballot_pb.js";
import type { LastRelayerCount, ObservationType } from "./relayer_pb.js";
import type { Chain } from "../pkg/chains/chains_pb.js";
import type { NodeAccount } from "./node_account_pb.js";
import type { CrosschainFlags } from "./crosschain_flags_pb.js";
import type { Keygen } from "./keygen_pb.js";
import type { Blame } from "./blame_pb.js";

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainNoncesRequest
 */
export declare class QueryGetChainNoncesRequest extends Message<QueryGetChainNoncesRequest> {
  /**
   * @generated from field: string index = 1;
   */
  index: string;

  constructor(data?: PartialMessage<QueryGetChainNoncesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainNoncesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainNoncesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainNoncesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainNoncesRequest;

  static equals(a: QueryGetChainNoncesRequest | PlainMessage<QueryGetChainNoncesRequest> | undefined, b: QueryGetChainNoncesRequest | PlainMessage<QueryGetChainNoncesRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainNoncesResponse
 */
export declare class QueryGetChainNoncesResponse extends Message<QueryGetChainNoncesResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.ChainNonces ChainNonces = 1;
   */
  ChainNonces?: ChainNonces;

  constructor(data?: PartialMessage<QueryGetChainNoncesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainNoncesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainNoncesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainNoncesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainNoncesResponse;

  static equals(a: QueryGetChainNoncesResponse | PlainMessage<QueryGetChainNoncesResponse> | undefined, b: QueryGetChainNoncesResponse | PlainMessage<QueryGetChainNoncesResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllChainNoncesRequest
 */
export declare class QueryAllChainNoncesRequest extends Message<QueryAllChainNoncesRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllChainNoncesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllChainNoncesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllChainNoncesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllChainNoncesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllChainNoncesRequest;

  static equals(a: QueryAllChainNoncesRequest | PlainMessage<QueryAllChainNoncesRequest> | undefined, b: QueryAllChainNoncesRequest | PlainMessage<QueryAllChainNoncesRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllChainNoncesResponse
 */
export declare class QueryAllChainNoncesResponse extends Message<QueryAllChainNoncesResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.ChainNonces ChainNonces = 1;
   */
  ChainNonces: ChainNonces[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryAllChainNoncesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllChainNoncesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllChainNoncesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllChainNoncesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllChainNoncesResponse;

  static equals(a: QueryAllChainNoncesResponse | PlainMessage<QueryAllChainNoncesResponse> | undefined, b: QueryAllChainNoncesResponse | PlainMessage<QueryAllChainNoncesResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllPendingNoncesRequest
 */
export declare class QueryAllPendingNoncesRequest extends Message<QueryAllPendingNoncesRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllPendingNoncesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllPendingNoncesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllPendingNoncesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllPendingNoncesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllPendingNoncesRequest;

  static equals(a: QueryAllPendingNoncesRequest | PlainMessage<QueryAllPendingNoncesRequest> | undefined, b: QueryAllPendingNoncesRequest | PlainMessage<QueryAllPendingNoncesRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllPendingNoncesResponse
 */
export declare class QueryAllPendingNoncesResponse extends Message<QueryAllPendingNoncesResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.PendingNonces pending_nonces = 1;
   */
  pendingNonces: PendingNonces[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryAllPendingNoncesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllPendingNoncesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllPendingNoncesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllPendingNoncesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllPendingNoncesResponse;

  static equals(a: QueryAllPendingNoncesResponse | PlainMessage<QueryAllPendingNoncesResponse> | undefined, b: QueryAllPendingNoncesResponse | PlainMessage<QueryAllPendingNoncesResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryPendingNoncesByChainRequest
 */
export declare class QueryPendingNoncesByChainRequest extends Message<QueryPendingNoncesByChainRequest> {
  /**
   * @generated from field: int64 chain_id = 1;
   */
  chainId: bigint;

  constructor(data?: PartialMessage<QueryPendingNoncesByChainRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryPendingNoncesByChainRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryPendingNoncesByChainRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryPendingNoncesByChainRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryPendingNoncesByChainRequest;

  static equals(a: QueryPendingNoncesByChainRequest | PlainMessage<QueryPendingNoncesByChainRequest> | undefined, b: QueryPendingNoncesByChainRequest | PlainMessage<QueryPendingNoncesByChainRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryPendingNoncesByChainResponse
 */
export declare class QueryPendingNoncesByChainResponse extends Message<QueryPendingNoncesByChainResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.PendingNonces pending_nonces = 1;
   */
  pendingNonces?: PendingNonces;

  constructor(data?: PartialMessage<QueryPendingNoncesByChainResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryPendingNoncesByChainResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryPendingNoncesByChainResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryPendingNoncesByChainResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryPendingNoncesByChainResponse;

  static equals(a: QueryPendingNoncesByChainResponse | PlainMessage<QueryPendingNoncesByChainResponse> | undefined, b: QueryPendingNoncesByChainResponse | PlainMessage<QueryPendingNoncesByChainResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTSSRequest
 */
export declare class QueryGetTSSRequest extends Message<QueryGetTSSRequest> {
  constructor(data?: PartialMessage<QueryGetTSSRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTSSRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTSSRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTSSRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTSSRequest;

  static equals(a: QueryGetTSSRequest | PlainMessage<QueryGetTSSRequest> | undefined, b: QueryGetTSSRequest | PlainMessage<QueryGetTSSRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTSSResponse
 */
export declare class QueryGetTSSResponse extends Message<QueryGetTSSResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.TSS TSS = 1;
   */
  TSS?: TSS;

  constructor(data?: PartialMessage<QueryGetTSSResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTSSResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTSSResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTSSResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTSSResponse;

  static equals(a: QueryGetTSSResponse | PlainMessage<QueryGetTSSResponse> | undefined, b: QueryGetTSSResponse | PlainMessage<QueryGetTSSResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTssAddressRequest
 */
export declare class QueryGetTssAddressRequest extends Message<QueryGetTssAddressRequest> {
  /**
   * @generated from field: int64 bitcoin_chain_id = 2;
   */
  bitcoinChainId: bigint;

  constructor(data?: PartialMessage<QueryGetTssAddressRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTssAddressRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTssAddressRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTssAddressRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTssAddressRequest;

  static equals(a: QueryGetTssAddressRequest | PlainMessage<QueryGetTssAddressRequest> | undefined, b: QueryGetTssAddressRequest | PlainMessage<QueryGetTssAddressRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTssAddressResponse
 */
export declare class QueryGetTssAddressResponse extends Message<QueryGetTssAddressResponse> {
  /**
   * @generated from field: string eth = 1;
   */
  eth: string;

  /**
   * @generated from field: string btc = 2;
   */
  btc: string;

  constructor(data?: PartialMessage<QueryGetTssAddressResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTssAddressResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTssAddressResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTssAddressResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTssAddressResponse;

  static equals(a: QueryGetTssAddressResponse | PlainMessage<QueryGetTssAddressResponse> | undefined, b: QueryGetTssAddressResponse | PlainMessage<QueryGetTssAddressResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTssAddressByFinalizedHeightRequest
 */
export declare class QueryGetTssAddressByFinalizedHeightRequest extends Message<QueryGetTssAddressByFinalizedHeightRequest> {
  /**
   * @generated from field: int64 finalized_pell_height = 1;
   */
  finalizedPellHeight: bigint;

  /**
   * @generated from field: int64 bitcoin_chain_id = 2;
   */
  bitcoinChainId: bigint;

  constructor(data?: PartialMessage<QueryGetTssAddressByFinalizedHeightRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTssAddressByFinalizedHeightRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTssAddressByFinalizedHeightRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTssAddressByFinalizedHeightRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTssAddressByFinalizedHeightRequest;

  static equals(a: QueryGetTssAddressByFinalizedHeightRequest | PlainMessage<QueryGetTssAddressByFinalizedHeightRequest> | undefined, b: QueryGetTssAddressByFinalizedHeightRequest | PlainMessage<QueryGetTssAddressByFinalizedHeightRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetTssAddressByFinalizedHeightResponse
 */
export declare class QueryGetTssAddressByFinalizedHeightResponse extends Message<QueryGetTssAddressByFinalizedHeightResponse> {
  /**
   * @generated from field: string eth = 1;
   */
  eth: string;

  /**
   * @generated from field: string btc = 2;
   */
  btc: string;

  constructor(data?: PartialMessage<QueryGetTssAddressByFinalizedHeightResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetTssAddressByFinalizedHeightResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetTssAddressByFinalizedHeightResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetTssAddressByFinalizedHeightResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetTssAddressByFinalizedHeightResponse;

  static equals(a: QueryGetTssAddressByFinalizedHeightResponse | PlainMessage<QueryGetTssAddressByFinalizedHeightResponse> | undefined, b: QueryGetTssAddressByFinalizedHeightResponse | PlainMessage<QueryGetTssAddressByFinalizedHeightResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryTssHistoryRequest
 */
export declare class QueryTssHistoryRequest extends Message<QueryTssHistoryRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryTssHistoryRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryTssHistoryRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTssHistoryRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTssHistoryRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTssHistoryRequest;

  static equals(a: QueryTssHistoryRequest | PlainMessage<QueryTssHistoryRequest> | undefined, b: QueryTssHistoryRequest | PlainMessage<QueryTssHistoryRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryTssHistoryResponse
 */
export declare class QueryTssHistoryResponse extends Message<QueryTssHistoryResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.TSS tss_list = 1;
   */
  tssList: TSS[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryTssHistoryResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryTssHistoryResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTssHistoryResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTssHistoryResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTssHistoryResponse;

  static equals(a: QueryTssHistoryResponse | PlainMessage<QueryTssHistoryResponse> | undefined, b: QueryTssHistoryResponse | PlainMessage<QueryTssHistoryResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryParamsRequest
 */
export declare class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryParamsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest;

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean;
}

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message pellchain.pellcore.relayer.QueryParamsResponse
 */
export declare class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: pellchain.pellcore.relayer.Params params = 1;
   */
  params?: Params;

  constructor(data?: PartialMessage<QueryParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse;

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryHasVotedRequest
 */
export declare class QueryHasVotedRequest extends Message<QueryHasVotedRequest> {
  /**
   * @generated from field: string ballot_identifier = 1;
   */
  ballotIdentifier: string;

  /**
   * @generated from field: string voter_address = 2;
   */
  voterAddress: string;

  constructor(data?: PartialMessage<QueryHasVotedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryHasVotedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryHasVotedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryHasVotedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryHasVotedRequest;

  static equals(a: QueryHasVotedRequest | PlainMessage<QueryHasVotedRequest> | undefined, b: QueryHasVotedRequest | PlainMessage<QueryHasVotedRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryHasVotedResponse
 */
export declare class QueryHasVotedResponse extends Message<QueryHasVotedResponse> {
  /**
   * @generated from field: bool has_voted = 1;
   */
  hasVoted: boolean;

  constructor(data?: PartialMessage<QueryHasVotedResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryHasVotedResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryHasVotedResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryHasVotedResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryHasVotedResponse;

  static equals(a: QueryHasVotedResponse | PlainMessage<QueryHasVotedResponse> | undefined, b: QueryHasVotedResponse | PlainMessage<QueryHasVotedResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBallotByIdentifierRequest
 */
export declare class QueryBallotByIdentifierRequest extends Message<QueryBallotByIdentifierRequest> {
  /**
   * @generated from field: string ballot_identifier = 1;
   */
  ballotIdentifier: string;

  constructor(data?: PartialMessage<QueryBallotByIdentifierRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBallotByIdentifierRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBallotByIdentifierRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBallotByIdentifierRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBallotByIdentifierRequest;

  static equals(a: QueryBallotByIdentifierRequest | PlainMessage<QueryBallotByIdentifierRequest> | undefined, b: QueryBallotByIdentifierRequest | PlainMessage<QueryBallotByIdentifierRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.VoterList
 */
export declare class VoterList extends Message<VoterList> {
  /**
   * @generated from field: string voter_address = 1;
   */
  voterAddress: string;

  /**
   * @generated from field: pellchain.pellcore.relayer.VoteType vote_type = 2;
   */
  voteType: VoteType;

  constructor(data?: PartialMessage<VoterList>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.VoterList";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoterList;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoterList;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoterList;

  static equals(a: VoterList | PlainMessage<VoterList> | undefined, b: VoterList | PlainMessage<VoterList> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBallotByIdentifierResponse
 */
export declare class QueryBallotByIdentifierResponse extends Message<QueryBallotByIdentifierResponse> {
  /**
   * @generated from field: string ballot_identifier = 1;
   */
  ballotIdentifier: string;

  /**
   * @generated from field: repeated pellchain.pellcore.relayer.VoterList voters = 2;
   */
  voters: VoterList[];

  /**
   * @generated from field: pellchain.pellcore.relayer.ObservationType observation_type = 3;
   */
  observationType: ObservationType;

  /**
   * @generated from field: pellchain.pellcore.relayer.BallotStatus ballot_status = 4;
   */
  ballotStatus: BallotStatus;

  constructor(data?: PartialMessage<QueryBallotByIdentifierResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBallotByIdentifierResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBallotByIdentifierResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBallotByIdentifierResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBallotByIdentifierResponse;

  static equals(a: QueryBallotByIdentifierResponse | PlainMessage<QueryBallotByIdentifierResponse> | undefined, b: QueryBallotByIdentifierResponse | PlainMessage<QueryBallotByIdentifierResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryObserverSet
 */
export declare class QueryObserverSet extends Message<QueryObserverSet> {
  constructor(data?: PartialMessage<QueryObserverSet>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryObserverSet";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryObserverSet;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryObserverSet;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryObserverSet;

  static equals(a: QueryObserverSet | PlainMessage<QueryObserverSet> | undefined, b: QueryObserverSet | PlainMessage<QueryObserverSet> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryObserverSetResponse
 */
export declare class QueryObserverSetResponse extends Message<QueryObserverSetResponse> {
  /**
   * @generated from field: repeated string observers = 1;
   */
  observers: string[];

  constructor(data?: PartialMessage<QueryObserverSetResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryObserverSetResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryObserverSetResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryObserverSetResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryObserverSetResponse;

  static equals(a: QueryObserverSetResponse | PlainMessage<QueryObserverSetResponse> | undefined, b: QueryObserverSetResponse | PlainMessage<QueryObserverSetResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QuerySupportedChains
 */
export declare class QuerySupportedChains extends Message<QuerySupportedChains> {
  constructor(data?: PartialMessage<QuerySupportedChains>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QuerySupportedChains";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QuerySupportedChains;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QuerySupportedChains;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QuerySupportedChains;

  static equals(a: QuerySupportedChains | PlainMessage<QuerySupportedChains> | undefined, b: QuerySupportedChains | PlainMessage<QuerySupportedChains> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QuerySupportedChainsResponse
 */
export declare class QuerySupportedChainsResponse extends Message<QuerySupportedChainsResponse> {
  /**
   * @generated from field: repeated chains.Chain chains = 1;
   */
  chains: Chain[];

  constructor(data?: PartialMessage<QuerySupportedChainsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QuerySupportedChainsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QuerySupportedChainsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QuerySupportedChainsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QuerySupportedChainsResponse;

  static equals(a: QuerySupportedChainsResponse | PlainMessage<QuerySupportedChainsResponse> | undefined, b: QuerySupportedChainsResponse | PlainMessage<QuerySupportedChainsResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainParamsForChainRequest
 */
export declare class QueryGetChainParamsForChainRequest extends Message<QueryGetChainParamsForChainRequest> {
  /**
   * @generated from field: int64 chain_id = 1;
   */
  chainId: bigint;

  constructor(data?: PartialMessage<QueryGetChainParamsForChainRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainParamsForChainRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainParamsForChainRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainParamsForChainRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainParamsForChainRequest;

  static equals(a: QueryGetChainParamsForChainRequest | PlainMessage<QueryGetChainParamsForChainRequest> | undefined, b: QueryGetChainParamsForChainRequest | PlainMessage<QueryGetChainParamsForChainRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainParamsForChainResponse
 */
export declare class QueryGetChainParamsForChainResponse extends Message<QueryGetChainParamsForChainResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.ChainParams chain_params = 1;
   */
  chainParams?: ChainParams;

  constructor(data?: PartialMessage<QueryGetChainParamsForChainResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainParamsForChainResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainParamsForChainResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainParamsForChainResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainParamsForChainResponse;

  static equals(a: QueryGetChainParamsForChainResponse | PlainMessage<QueryGetChainParamsForChainResponse> | undefined, b: QueryGetChainParamsForChainResponse | PlainMessage<QueryGetChainParamsForChainResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainParamsRequest
 */
export declare class QueryGetChainParamsRequest extends Message<QueryGetChainParamsRequest> {
  constructor(data?: PartialMessage<QueryGetChainParamsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainParamsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainParamsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainParamsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainParamsRequest;

  static equals(a: QueryGetChainParamsRequest | PlainMessage<QueryGetChainParamsRequest> | undefined, b: QueryGetChainParamsRequest | PlainMessage<QueryGetChainParamsRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetChainParamsResponse
 */
export declare class QueryGetChainParamsResponse extends Message<QueryGetChainParamsResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.ChainParamsList chain_params = 1;
   */
  chainParams?: ChainParamsList;

  constructor(data?: PartialMessage<QueryGetChainParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetChainParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetChainParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetChainParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetChainParamsResponse;

  static equals(a: QueryGetChainParamsResponse | PlainMessage<QueryGetChainParamsResponse> | undefined, b: QueryGetChainParamsResponse | PlainMessage<QueryGetChainParamsResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetNodeAccountRequest
 */
export declare class QueryGetNodeAccountRequest extends Message<QueryGetNodeAccountRequest> {
  /**
   * @generated from field: string index = 1;
   */
  index: string;

  constructor(data?: PartialMessage<QueryGetNodeAccountRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetNodeAccountRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetNodeAccountRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetNodeAccountRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetNodeAccountRequest;

  static equals(a: QueryGetNodeAccountRequest | PlainMessage<QueryGetNodeAccountRequest> | undefined, b: QueryGetNodeAccountRequest | PlainMessage<QueryGetNodeAccountRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetNodeAccountResponse
 */
export declare class QueryGetNodeAccountResponse extends Message<QueryGetNodeAccountResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.NodeAccount node_account = 1;
   */
  nodeAccount?: NodeAccount;

  constructor(data?: PartialMessage<QueryGetNodeAccountResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetNodeAccountResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetNodeAccountResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetNodeAccountResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetNodeAccountResponse;

  static equals(a: QueryGetNodeAccountResponse | PlainMessage<QueryGetNodeAccountResponse> | undefined, b: QueryGetNodeAccountResponse | PlainMessage<QueryGetNodeAccountResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllNodeAccountRequest
 */
export declare class QueryAllNodeAccountRequest extends Message<QueryAllNodeAccountRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllNodeAccountRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllNodeAccountRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllNodeAccountRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllNodeAccountRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllNodeAccountRequest;

  static equals(a: QueryAllNodeAccountRequest | PlainMessage<QueryAllNodeAccountRequest> | undefined, b: QueryAllNodeAccountRequest | PlainMessage<QueryAllNodeAccountRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllNodeAccountResponse
 */
export declare class QueryAllNodeAccountResponse extends Message<QueryAllNodeAccountResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.NodeAccount NodeAccount = 1;
   */
  NodeAccount: NodeAccount[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryAllNodeAccountResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllNodeAccountResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllNodeAccountResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllNodeAccountResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllNodeAccountResponse;

  static equals(a: QueryAllNodeAccountResponse | PlainMessage<QueryAllNodeAccountResponse> | undefined, b: QueryAllNodeAccountResponse | PlainMessage<QueryAllNodeAccountResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetCrosschainFlagsRequest
 */
export declare class QueryGetCrosschainFlagsRequest extends Message<QueryGetCrosschainFlagsRequest> {
  constructor(data?: PartialMessage<QueryGetCrosschainFlagsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetCrosschainFlagsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetCrosschainFlagsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetCrosschainFlagsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetCrosschainFlagsRequest;

  static equals(a: QueryGetCrosschainFlagsRequest | PlainMessage<QueryGetCrosschainFlagsRequest> | undefined, b: QueryGetCrosschainFlagsRequest | PlainMessage<QueryGetCrosschainFlagsRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetCrosschainFlagsResponse
 */
export declare class QueryGetCrosschainFlagsResponse extends Message<QueryGetCrosschainFlagsResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.CrosschainFlags crosschain_flags = 1;
   */
  crosschainFlags?: CrosschainFlags;

  constructor(data?: PartialMessage<QueryGetCrosschainFlagsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetCrosschainFlagsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetCrosschainFlagsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetCrosschainFlagsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetCrosschainFlagsResponse;

  static equals(a: QueryGetCrosschainFlagsResponse | PlainMessage<QueryGetCrosschainFlagsResponse> | undefined, b: QueryGetCrosschainFlagsResponse | PlainMessage<QueryGetCrosschainFlagsResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetKeygenRequest
 */
export declare class QueryGetKeygenRequest extends Message<QueryGetKeygenRequest> {
  constructor(data?: PartialMessage<QueryGetKeygenRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetKeygenRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetKeygenRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetKeygenRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetKeygenRequest;

  static equals(a: QueryGetKeygenRequest | PlainMessage<QueryGetKeygenRequest> | undefined, b: QueryGetKeygenRequest | PlainMessage<QueryGetKeygenRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryGetKeygenResponse
 */
export declare class QueryGetKeygenResponse extends Message<QueryGetKeygenResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.Keygen keygen = 1;
   */
  keygen?: Keygen;

  constructor(data?: PartialMessage<QueryGetKeygenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryGetKeygenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryGetKeygenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryGetKeygenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryGetKeygenResponse;

  static equals(a: QueryGetKeygenResponse | PlainMessage<QueryGetKeygenResponse> | undefined, b: QueryGetKeygenResponse | PlainMessage<QueryGetKeygenResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryShowObserverCountRequest
 */
export declare class QueryShowObserverCountRequest extends Message<QueryShowObserverCountRequest> {
  constructor(data?: PartialMessage<QueryShowObserverCountRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryShowObserverCountRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryShowObserverCountRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryShowObserverCountRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryShowObserverCountRequest;

  static equals(a: QueryShowObserverCountRequest | PlainMessage<QueryShowObserverCountRequest> | undefined, b: QueryShowObserverCountRequest | PlainMessage<QueryShowObserverCountRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryShowObserverCountResponse
 */
export declare class QueryShowObserverCountResponse extends Message<QueryShowObserverCountResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.LastRelayerCount last_observer_count = 1;
   */
  lastObserverCount?: LastRelayerCount;

  constructor(data?: PartialMessage<QueryShowObserverCountResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryShowObserverCountResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryShowObserverCountResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryShowObserverCountResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryShowObserverCountResponse;

  static equals(a: QueryShowObserverCountResponse | PlainMessage<QueryShowObserverCountResponse> | undefined, b: QueryShowObserverCountResponse | PlainMessage<QueryShowObserverCountResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBlameByIdentifierRequest
 */
export declare class QueryBlameByIdentifierRequest extends Message<QueryBlameByIdentifierRequest> {
  /**
   * @generated from field: string blame_identifier = 1;
   */
  blameIdentifier: string;

  constructor(data?: PartialMessage<QueryBlameByIdentifierRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBlameByIdentifierRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlameByIdentifierRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlameByIdentifierRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlameByIdentifierRequest;

  static equals(a: QueryBlameByIdentifierRequest | PlainMessage<QueryBlameByIdentifierRequest> | undefined, b: QueryBlameByIdentifierRequest | PlainMessage<QueryBlameByIdentifierRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBlameByIdentifierResponse
 */
export declare class QueryBlameByIdentifierResponse extends Message<QueryBlameByIdentifierResponse> {
  /**
   * @generated from field: pellchain.pellcore.relayer.Blame blame_info = 1;
   */
  blameInfo?: Blame;

  constructor(data?: PartialMessage<QueryBlameByIdentifierResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBlameByIdentifierResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlameByIdentifierResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlameByIdentifierResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlameByIdentifierResponse;

  static equals(a: QueryBlameByIdentifierResponse | PlainMessage<QueryBlameByIdentifierResponse> | undefined, b: QueryBlameByIdentifierResponse | PlainMessage<QueryBlameByIdentifierResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllBlameRecordsRequest
 */
export declare class QueryAllBlameRecordsRequest extends Message<QueryAllBlameRecordsRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAllBlameRecordsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllBlameRecordsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllBlameRecordsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllBlameRecordsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllBlameRecordsRequest;

  static equals(a: QueryAllBlameRecordsRequest | PlainMessage<QueryAllBlameRecordsRequest> | undefined, b: QueryAllBlameRecordsRequest | PlainMessage<QueryAllBlameRecordsRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryAllBlameRecordsResponse
 */
export declare class QueryAllBlameRecordsResponse extends Message<QueryAllBlameRecordsResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.Blame blame_info = 1;
   */
  blameInfo: Blame[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryAllBlameRecordsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryAllBlameRecordsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAllBlameRecordsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAllBlameRecordsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAllBlameRecordsResponse;

  static equals(a: QueryAllBlameRecordsResponse | PlainMessage<QueryAllBlameRecordsResponse> | undefined, b: QueryAllBlameRecordsResponse | PlainMessage<QueryAllBlameRecordsResponse> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBlameByChainAndNonceRequest
 */
export declare class QueryBlameByChainAndNonceRequest extends Message<QueryBlameByChainAndNonceRequest> {
  /**
   * @generated from field: int64 chain_id = 1;
   */
  chainId: bigint;

  /**
   * @generated from field: int64 nonce = 2;
   */
  nonce: bigint;

  constructor(data?: PartialMessage<QueryBlameByChainAndNonceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBlameByChainAndNonceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlameByChainAndNonceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlameByChainAndNonceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlameByChainAndNonceRequest;

  static equals(a: QueryBlameByChainAndNonceRequest | PlainMessage<QueryBlameByChainAndNonceRequest> | undefined, b: QueryBlameByChainAndNonceRequest | PlainMessage<QueryBlameByChainAndNonceRequest> | undefined): boolean;
}

/**
 * @generated from message pellchain.pellcore.relayer.QueryBlameByChainAndNonceResponse
 */
export declare class QueryBlameByChainAndNonceResponse extends Message<QueryBlameByChainAndNonceResponse> {
  /**
   * @generated from field: repeated pellchain.pellcore.relayer.Blame blame_info = 1;
   */
  blameInfo: Blame[];

  constructor(data?: PartialMessage<QueryBlameByChainAndNonceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pellchain.pellcore.relayer.QueryBlameByChainAndNonceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBlameByChainAndNonceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBlameByChainAndNonceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBlameByChainAndNonceResponse;

  static equals(a: QueryBlameByChainAndNonceResponse | PlainMessage<QueryBlameByChainAndNonceResponse> | undefined, b: QueryBlameByChainAndNonceResponse | PlainMessage<QueryBlameByChainAndNonceResponse> | undefined): boolean;
}

