name: Buf push

on:
  # Apply to all pushes on 'main' branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: "1.47.2"
      # Run a lint check on Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
      # Run breaking change detection for Protobuf sources against the current
      # `main` branch, 'proto' subdirectory
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     against: 'https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/0xPellNetwork/chain.git#branch=main,ref=HEAD~1,subdir=proto'
      # Push the validated module to the BSR
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: proto