name: Generated Files Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  generate-check:
    name: Verify
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Install buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Install tools
      run: |
        go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v1.16.0
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/cosmos/gogoproto/protoc-gen-gocosmos
        go install github.com/vektra/mockery/v2@v2.48.0
        
    - name: Generate proto files
      run: make proto

    - name: Generate mocks
      run: cd testutil/keeper/mocks && go generate ./...


    - name: Verify generated files
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Error: Generated files are not up to date."
          git status
          git diff
          exit 1
        fi 