name: Goimports Lint
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  generate-check:
    name: Verify
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Install tools
      run: |
        go install github.com/incu6us/goimports-reviser/v3@latest
        
    - name: Format imports
      run: make lint-imports

    - name: Verify goimports
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Error: Goimports are not up to date."
          echo "Please run 'make lint-imports' locally and commit the changes."
          git status
          git diff
          exit 1
        fi 